[SonLVL]
revision=750
;description=The main program.\nAdding custom background color option.
description=The main program.\nPretend there's some cool change here.\nAdded Luigi.
file=SonLVL.zip

[LevelConverter]
revision=25
description=Converts levels between games.\nFix S2NA support.
file=LevelConverter.zip

[SonAni]
revision=10
description=Edits animations.\nFixed scrollbar limits.
file=SonAni.zip

[ObjectLayoutDiff]
revision=9
description=Creates and applies diffs of object layout files.\nFix S2NA support.
file=ObjectLayoutDiff.zip

[SpriteSheetGen]
revision=11
description=Generates sprite sheets.\nAlign sprite centers when generating a grid.
file=SpriteSheetGen.zip

[SpritePlotter.NET]
revision=10
description=Generates sprite mappings from images.\nReplace spaces in labels with underscores.
file=SpritePlotter.NET.zip

[GetArt.NET]
revision=4
description=Generates plane mappings from images.\nRolling back to .NET 4.6.
file=GetArt.NET.zip

[S1SSEdit]
revision=8
description=Sonic 1 Special Stage editor.\nFix startup crash with grid enabled.
file=S1SSEdit.zip

[S3SSEdit]
revision=12
description=Sonic 3 & Knuckles Special Stage editor.\nAdding upper limit on Perfect count.
file=S3SSEdit.zip

[ObjectLayoutMerge]
revision=16
description=Compares and merges changes between two object layouts.\nFix S2NA support.
file=ObjectLayoutMerge.zip

[SonPLN]
revision=23
description=Plane mappings editor.\nVarious bugfixes.
file=SonPLN.zip

; SonED2 tools: (Deprecated, though still present on the repo)

;[SonED2ProjectConverter]
;revision=4
;description=Converts SonED2 projects to SonLVL format.\nRolling back to .NET 4.6.
;file=SonED2ProjectConverter.zip

; Deprecated (though still present in the project file)
;[SonED2ObjDefConverter]
;revision=4
;description=Converts SonED2 object definitions to SonLVL format.\nRolling back to .NET 4.6.
;file=SonED2ObjDefConverter.zip
