[DEZ/DeathEggRobot.txt]
name=Death Egg Robot
codefile=DEZ/DeathEggRobot.cs
codetype=S2ObjectDefinitions.DEZ.DeathEggRobot
[DEZ/DERArm.txt]
name=DER Arm
codefile=DEZ/DERGeneric.cs
codetype=S2ObjectDefinitions.DEZ.DERArm
[DEZ/DERBomb.txt]
name=DER Bomb
codefile=DEZ/DERGeneric.cs
codetype=S2ObjectDefinitions.DEZ.DERBomb
[DEZ/DERFoot.txt]
name=DER Foot
codefile=DEZ/DERGeneric.cs
codetype=S2ObjectDefinitions.DEZ.DERFoot
[DEZ/DERHand.txt]
name=DER Hand
codefile=DEZ/DERGeneric.cs
codetype=S2ObjectDefinitions.DEZ.DERHand
[DEZ/DERLeg.txt]
name=DER Leg
codefile=DEZ/DERGeneric.cs
codetype=S2ObjectDefinitions.DEZ.DERLeg
[DEZ/DERShoulder.txt]
name=DER Shoulder
codefile=DEZ/DERGeneric.cs
codetype=S2ObjectDefinitions.DEZ.DERShoulder
[DEZ/DERTarget.txt]
name=DER Target
codefile=DEZ/DERGeneric.cs
codetype=S2ObjectDefinitions.DEZ.DERTarget
[DEZ/DEZSetup.txt]
name=DEZ Setup
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
hidden=true
[DEZ/Eggman.txt]
; called "DEZ Eggman" in MBZ, but we'll stick with the normal name here
name=Eggman
codefile=DEZ/DERGeneric.cs
codetype=S2AObjectDefinitions.DEZ.Eggman
[DEZ/EggmanWindow.txt]
name=Eggman Window
codefile=DEZ/DERGeneric.cs
codetype=S2ObjectDefinitions.DEZ.EggmanWindow
[DEZ/MechaSonic.txt]
name=Mecha Sonic
codefile=DEZ/DERGeneric.cs
codetype=S2ObjectDefinitions.DEZ.MechaSonic
[DEZ/MechaSonicSpike.txt]
name=MechaSonicSpike
codefile=DEZ/DERGeneric.cs
codetype=S2ObjectDefinitions.DEZ.MechaSonicSpike
[DEZ/OneWayDoor.txt]
; loading CPZ on purpose (base game loads CPZ sheet in DEZ too)
name=One Way Door
codefile=CPZ/OneWayDoor.cs
codetype=S2AObjectDefinitions.DEZ.OneWayDoor
