[EHZ/Bridge.txt]
name=Bridge
codefile=EHZ/Bridge.cs
codetype=S2ObjectDefinitions.EHZ.Bridge
[EHZ/BridgeEnd.txt]
name=Bridge End
codefile=EHZ/Generic.cs
codetype=S2ObjectDefinitions.EHZ.BridgeEnd
[EHZ/BurningLog.txt]
name=Burning Log
codefile=EHZ/Generic.cs
codetype=S2ObjectDefinitions.EHZ.BurningLog
[EHZ/Eggman.txt]
; called "EHZ Eggman" in MBZ, but we'll stick with the normal name here
name=Eggman
codefile=EHZ/Generic.cs
codetype=S2ObjectDefinitions.EHZ.Eggman
[EHZ/EggmanCar.txt]
name=Eggman Car
codefile=EHZ/Generic.cs
codetype=S2ObjectDefinitions.EHZ.EggmanCar
[EHZ/EggmanDrill.txt]
name=Eggman Drill
codefile=EHZ/Generic.cs
codetype=S2ObjectDefinitions.EHZ.EggmanDrill
[EHZ/EggmanWheel.txt]
name=Eggman Wheel
codefile=EHZ/Generic.cs
codetype=S2ObjectDefinitions.EHZ.EggmanWheel
[EHZ/EHZSetup.txt]
name=EHZ Setup
hidden=true
[EHZ/ExhaustPuff.txt]
name=Exhaust Puff
codefile=EHZ/Generic.cs
codetype=S2ObjectDefinitions.EHZ.ExhaustPuff
[EHZ/FlowerSaver.txt]
name=Flower Saver
codefile=EHZ/FlowerSaver.cs
codetype=S2AObjectDefinitions.EHZ.FlowerSaver
[EHZ/FPlatform.txt]
name=Fall Platform
codefile=EHZ/FPlatform.cs
codetype=S2ObjectDefinitions.EHZ.FPlatform
[EHZ/HPlatform.txt]
name=H Platform
codefile=EHZ/Platform.cs
codetype=S2ObjectDefinitions.EHZ.HPlatform
[EHZ/NoTitleCard.txt]
name=Blank Title Card
hidden=true
[EHZ/ObjectActivator.txt]
name=Object Activator
codefile=EHZ/ObjectActivator.cs
codetype=S2ObjectDefinitions.EHZ.ObjectActivator
[EHZ/SpiralPath.txt]
name=Spiral Path
codefile=EHZ/SpiralPath.cs
codetype=S2ObjectDefinitions.EHZ.SpiralPath
[EHZ/VPlatform.txt]
name=V Platform
codefile=EHZ/Platform.cs
codetype=S2ObjectDefinitions.EHZ.VPlatform
[EHZ/VPlatform2.txt]
name=V Platform 2
codefile=EHZ/Platform.cs
codetype=S2ObjectDefinitions.EHZ.VPlatform2
[EHZ/Waterfall.txt]
name=Waterfall
codefile=EHZ/Waterfall.cs
codetype=S2AObjectDefinitions.EHZ.Waterfall
