[HTZ/2PVsDeleter.txt]
name=2P Vs Deleter
codefile=HTZ/VsDeleter.cs
codetype=S2ObjectDefinitions.HTZ.VsDeleter
[HTZ/BreakBlock.txt]
name=Break Block
codefile=HTZ/BreakBlock.cs
codetype=S2ObjectDefinitions.HTZ.BreakBlock
[HTZ/BreakRock.txt]
name=Break Rock
sheet=HTZ/Objects.gif
frame=-24, -16, 48, 32, 207, 94
[HTZ/Earthquake.txt]
name=Earthquake
xmlfile=HTZ/Earthquake.xml
[HTZ/Eggman.txt]
; called "HTZ Eggman" in MBZ, but we'll stick with the normal name here
name=Eggman
codefile=HTZ/Eggman.cs
codetype=S2ObjectDefinitions.HTZ.Eggman
[HTZ/EggmanFireball1.txt]
; called Eggman Fireball1 (no space) in HTZ while MBZ has a space
; we'll stick with the former here
name=Eggman Fireball1
codefile=HTZ/Generic.cs
codetype=S2ObjectDefinitions.HTZ.EggmanFireball1
[HTZ/EggmanFireball2.txt]
; ditto, called Eggman Fireball2 (no space) in HTZ while MBZ has a space
; we'll stick with the former here again
name=Eggman Fireball2
codefile=HTZ/Generic.cs
codetype=S2ObjectDefinitions.HTZ.EggmanFireball2
[HTZ/EgmanSmokePuff.txt]
name=Eggman SmokePuff
codefile=HTZ/Generic.cs
codetype=S2ObjectDefinitions.HTZ.EggmanSmokePuff
[HTZ/FPlatform.txt]
name=Fall Platform
codefile=HTZ/FPlatform.cs
codetype=S2ObjectDefinitions.HTZ.FPlatform
[HTZ/GroundFlame.txt]
name=Ground Flame
codefile=HTZ/Generic.cs
codetype=S2ObjectDefinitions.HTZ.GroundFlame
[HTZ/HPlatform.txt]
name=H Platform
codefile=HTZ/Platform.cs
codetype=S2ObjectDefinitions.HTZ.HPlatform
[HTZ/HTZSetup.txt]
name=HTZ Setup
hidden=true
[HTZ/LavaBubble.txt]
name=Lava Bubble
codefile=HTZ/Generic.cs
codetype=S2ObjectDefinitions.HTZ.LavaBubble
[HTZ/LavaJump.txt]
name=Lava Jump
codefile=HTZ/Generic.cs
codetype=S2ObjectDefinitions.HTZ.LavaJump
[HTZ/Lift.txt]
name=Lift
codefile=HTZ/Lift.cs
codetype=S2ObjectDefinitions.HTZ.Lift
[HTZ/LiftEnd.txt]
name=Lift End
codefile=HTZ/LiftEnd.cs
codetype=S2ObjectDefinitions.HTZ.LiftEnd
[HTZ/OneWayDoor.txt]
name=One Way Door
xmlfile=HTZ/OneWayDoor.xml
[HTZ/SeeSaw.txt]
name=SeeSaw
xmlfile=HTZ/SeeSaw.xml
[HTZ/TubeSwitch.txt]
name=Tube Switch
xmlfile=HTZ/TubeSwitch.xml
[HTZ/VPlatform.txt]
name=V Platform
codefile=HTZ/Platform.cs
codetype=S2ObjectDefinitions.HTZ.VPlatform
[HTZ/VPlatform2.txt]
name=V Platform 2
codefile=HTZ/Platform.cs
codetype=S2ObjectDefinitions.HTZ.VPlatform2
