[MCZ/BossRock.txt]
name=Boss Rock
codefile=MCZ/Generic.cs
codetype=S2ObjectDefinitions.MCZ.BossRock
[MCZ/CollapsingLedge.txt]
name=C Ledge
codefile=MCZ/CollapsingLedge.cs
codetype=S2ObjectDefinitions.MCZ.CLedge
[MCZ/Eggman.txt]
; called "MCZ Eggman" in MBZ, but we'll stick with the normal name here
name=Eggman
codefile=MCZ/Generic.cs
codetype=S2ObjectDefinitions.MCZ.Eggman
[MCZ/EggmanDrill.txt]
; called Eggman Drill 2 in MBZ, since EHZ took the "Eggman Drill" name already
; we'll stick with the normal name here
name=Eggman Drill
codefile=MCZ/Generic.cs
codetype=S2ObjectDefinitions.MCZ.EggmanDrill
[MCZ/HDropBridge.txt]
name=H Drop Bridge
codefile=MCZ/HDropBridge.cs
codetype=S2ObjectDefinitions.MCZ.HDropBridge
[MCZ/HPlatform.txt]
name=H Platform
codefile=MCZ/HPlatform.cs
codetype=S2ObjectDefinitions.MCZ.HPlatform
[MCZ/HPZTrigger.txt]
name=HPZ Trigger
codefile=MCZ/HPZTrigger.cs
codetype=S2ObjectDefinitions.MCZ.HPZTrigger
[MCZ/MCZSetup.txt]
name=MCZ Setup
hidden=true
[MCZ/MovingCrates.txt]
name=Moving Crates
codefile=MCZ/MovingCrates.cs
codetype=S2ObjectDefinitions.MCZ.MovingCrates
[MCZ/PullSwitch.txt]
name=Pull Switch
sheet=MCZ/Objects.gif
frame=-8, -48, 16, 95, 215, 161
[MCZ/PullVine.txt]
name=Pull Vine
codefile=MCZ/PullVine.cs
codetype=S2ObjectDefinitions.MCZ.PullVine
[MCZ/RingPlatform.txt]
name=Ring Platform
codefile=MCZ/RingPlatform.cs
codetype=S2ObjectDefinitions.MCZ.RingPlatform
[MCZ/RockCrusher.txt]
name=Rock Crusher
codefile=MCZ/RockCrusher.cs
codetype=S2ObjectDefinitions.MCZ.RockCrusher
[MCZ/RotatingSpike.txt]
; called RotatingSpike (with no space) in Origins's missions, but we'll keep the space here
name=Rotating Spike
codefile=MCZ/RotatingSpike.cs
codetype=S2ObjectDefinitions.MCZ.RotatingSpike
[MCZ/SpikedLedge.txt]
name=Spiked Ledge
codefile=MCZ/SpikedLedge.cs
codetype=S2ObjectDefinitions.MCZ.SpikedLedge
[MCZ/StaticBlock.txt]
; the only reason we really need this xml is cause there's a random block with YFlip set in MCZ1
; otherwise, we could've just left it as a basic render...
name=Static Block
xmlfile=MCZ/StaticBlock.xml
[MCZ/SwingPlat.txt]
name=Swing Platform
codefile=MCZ/SwingPlat.cs
codetype=S2ObjectDefinitions.MCZ.SwingPlatform
[MCZ/SwingSpikes.txt]
name=Swing Spikes
codefile=MCZ/SwingSpikes.cs
codetype=S2ObjectDefinitions.MCZ.SwingSpikes
[MCZ/VDropBridge.txt]
name=V Drop Bridge
codefile=MCZ/VDropBridge.cs
codetype=S2ObjectDefinitions.MCZ.VDropBridge
