[OOZ/BallCannon.txt]
name=Ball Cannon
codefile=OOZ/BallCannon.cs
codetype=S2ObjectDefinitions.OOZ.BallCannon
[OOZ/BreakBlock.txt]
name=Gas Break Block
codefile=OOZ/BreakBlock.cs
codetype=S2ObjectDefinitions.OOZ.GasBreakBlock
[OOZ/CheckeredBall.txt]
name=Checkered Ball
sheet=OOZ/Objects.gif
frame=-16, -16, 32, 32, 429, 190
[OOZ/CollapsingFloor.txt]
name=C Floor
codefile=OOZ/CollapsingFloor.cs
codetype=S2ObjectDefinitions.OOZ.CFloor
[OOZ/Eggman.txt]
; called "OOZ Eggman" in MBZ, but we'll stick with the normal name here
name=Eggman
codefile=OOZ/Generic.cs
codetype=S2ObjectDefinitions.OOZ.Eggman
[OOZ/EggmanCannon.txt]
name=Eggman Cannon
codefile=OOZ/Generic.cs
codetype=S2ObjectDefinitions.OOZ.EggmanCannon
[OOZ/EggmanFlame.txt]
name=Eggman Flame
codefile=OOZ/Generic.cs
codetype=S2ObjectDefinitions.OOZ.EggmanFlame
[OOZ/EggmanHarpoon.txt]
name=Eggman Harpoon
codefile=OOZ/Generic.cs
codetype=S2ObjectDefinitions.OOZ.EggmanHarpoon
[OOZ/EggmanLaser.txt]
name=Eggman Laser
codefile=OOZ/Generic.cs
codetype=S2ObjectDefinitions.OOZ.EggmanLaser
[OOZ/Elevator.txt]
name=Elevator
codefile=OOZ/Elevator.cs
codetype=S2ObjectDefinitions.OOZ.Elevator
[OOZ/GasPlatform.txt]
name=Gas Platform
codefile=OOZ/GasPlatform.cs
codetype=S2ObjectDefinitions.OOZ.GasPlatform
[OOZ/HFan.txt]
name=H Fan
codefile=OOZ/HFan.cs
codetype=S2ObjectDefinitions.OOZ.HFan
[OOZ/HPushSpring.txt]
name=H Push Spring
codefile=OOZ/HPushSpring.cs
codetype=S2ObjectDefinitions.OOZ.HPushSpring
[OOZ/MovingSpikes.txt]
name=Moving Spikes
codefile=OOZ/MovingSpikes.cs
codetype=S2ObjectDefinitions.OOZ.MovingSpikes
[OOZ/OilFall.txt]
name=Oil Fall
codefile=OOZ/OilFall.cs
codetype=S2ObjectDefinitions.OOZ.OilFall
[OOZ/OOZSetup.txt]
name=OOZ Setup
hidden=true
[OOZ/PushButton.txt]
name=Push Button
sheet=MPZ/Objects.gif
frame=-16, -8, 32, 16, 317, 190
[OOZ/SpikesActivator.txt]
name=Spikes Activator
codefile=OOZ/SpikesActivator.cs
codetype=S2ObjectDefinitions.OOZ.SpikesActivator
[OOZ/SwingPlat.txt]
name=Swing Platform
codefile=OOZ/SwingPlat.cs
codetype=S2ObjectDefinitions.OOZ.SwingPlatform
[OOZ/VFan.txt]
name=V Fan
codefile=OOZ/VFan.cs
codetype=S2ObjectDefinitions.OOZ.VFan
[OOZ/VPushSpring.txt]
name=V Push Spring
xmlfile=OOZ/VPushSpring.xml
