[Title/ControlTest.txt]
name=Control Test
sheet=Title/ControlTest.gif
frame=176, 100, 28, 28, 351, 1
[Title/Sega.txt]
name=Sega
sheet=Title/Title.gif
frame=-31, -36, 62, 72, 1, 226
[Title/STScreen.txt]
; object is made out of tiles, so no render of that possible...
; (sure, we *could* draw tiles in the object sprite with a C# def, but.. that's a bit overkill-)
name=ST Screen
hidden=true
[Title/STLogo.txt]
name=ST Logo
sheet=Title/Title.gif
frame=-128, -78, 256, 82, 255, 67
hidden=true
[Title/KLogo.txt]
name=K Logo
xmlfile=Title/STLogo.xml
[Title/TinkleStars.txt]
name=Twinkle Stars
sheet=Title/Title.gif
frame=-12, -12, 23, 23, 441, 43
hidden=true
[Title/ShootingStar.txt]
name=Shooting Star
sheet=Title/Title.gif
frame=-4, -4, 7, 7, 417, 59
hidden=true
[Title/Start.txt]
name=Start Message
sheet=Title/Title.gif
frame=-45, -1, 90, 9, 1, 370
hidden=true
