[R1/Amy.txt]
name=Amy Rose
sheet=R1/Objects.gif
frame=-11, -20, 22, 40, 34, 208
[R1/Anton.txt]
name=Anton
xmlfile=R1/Anton.xml
[R1/BGFX_R11A.txt]
; (obj is spawned by Ramp3D triggers)
name=Background FX
hidden=true
[R1/BoostSpinner.txt]
name=Boost Spinner
sheet=R1/Objects2.gif
frame=-24, -24, 48, 48, 1, 82
[R1/Boss_Arm.txt]
name=Boss Arm
sheet=R1/Objects3.gif
frame=-15, -8, 32, 16, 141, 34
hidden=true
[R1/Boss_ArmJoint.txt]
name=Boss Arm Joint
sheet=R1/Objects3.gif
frame=-8, -8, 16, 16, 124, 34
hidden=true
[R1/Boss_Body.txt]
name=Boss Body
sheet=R1/Objects3.gif
frame=-36, -32, 72, 64, 1, 1
hidden=true
[R1/Boss_Bumper.txt]
name=Boss Bumper
sheet=R1/Objects3.gif
frame=-14, -16, 24, 32, 99, 26
hidden=true
[R1/Boss_Face.txt]
name=Boss Face
xmlfile=R1/Boss_Face.xml
[R1/Boss_Foot.txt]
name=Boss Foot
sheet=R1/Objects3.gif
frame=-32, -20, 58, 40, 1, 66
hidden=true
[R1/Boss_Leg.txt]
name=Boss Leg
sheet=R1/Objects3.gif
frame=-12, -20, 24, 40, 74, 1
hidden=true
[R1/Boss_LegJoint.txt]
name=Boss Leg Joint
sheet=R1/Objects3.gif
frame=-8, -8, 16, 16, 74, 42
hidden=true
[R1/Boss_Shoulder.txt]
name=Boss Shoulder
sheet=R1/Objects3.gif
frame=-24, -12, 40, 24, 66, 66
hidden=true
[R1/BouncePole.txt]
name=Bounce Pole
xmlfile=R1/BouncePole.xml
[R1/BoundsTriggerV.txt]
; new Origins Plus obj
name=Bounds Trigger V
codefile=R1/BoundsTriggerV.cs
codetype=SCDObjectDefinitions.R1.BoundsTriggerV
[R1/BreakWall.txt]
name=Breakable Wall
codefile=R1/BreakWall.cs
codetype=SCDObjectDefinitions.R1.BreakWall
[R1/Bullet.txt]
name=Bullet
sheet=R1/Objects.gif
frame=-4, -4, 8, 8, 166, 34
hidden=true
[R1/CLedge1.txt]
name=Crumble Ledge 1
codefile=R1/CLedge12.cs
codetype=SCDObjectDefinitions.R1.CLedge1
[R1/CLedge2.txt]
name=Crumble Ledge 2
codefile=R1/CLedge12.cs
codetype=SCDObjectDefinitions.R1.CLedge2
[R1/CLedge3.txt]
name=Crumble Ledge 3
codefile=R1/CLedge34.cs
codetype=SCDObjectDefinitions.R1.CLedge3
[R1/CLedge4.txt]
name=Crumble Ledge 4
codefile=R1/CLedge34.cs
codetype=SCDObjectDefinitions.R1.CLedge4
[R1/CLedge5.txt]
name=Crumble Ledge 5
codefile=R1/CLedge5.cs
codetype=SCDObjectDefinitions.R1.CLedge5
[R1/DPlatform.txt]
name=Diag Platform
codefile=R1/Platform.cs
codetype=SCDObjectDefinitions.R1.DPlatform
[R1/EggJetpack.txt]
name=Eggman Jetpack
sheet=R1/Objects3.gif
frame=-28, -24, 56, 56, 1, 107
hidden=true
[R1/FlipDoor.txt]
name=Flip Door
xmlfile=R1/FlipDoor.xml
[R1/Flower.txt]
name=Flower
sheet=R1/Objects2.gif
frame=-4, -8, 8, 16, 180, 1
hidden=true
[R1/FPlatform.txt]
name=Fall Platform
codefile=R1/Platform.cs
codetype=SCDObjectDefinitions.R1.FPlatform
[R1/HPlatform.txt]
name=Horz Platform
codefile=R1/Platform.cs
codetype=SCDObjectDefinitions.R1.HPlatform
[R1/InvBlock.txt]
name=Invisible Block
sheet=R1/Objects.gif
frame=-12, -12, 24, 24, 68, 142
[R1/InvisibleBlock.txt]
; new Origins Plus obj (yeah it's actually called "Invisivle Block" in-game, that's not a typo haha)
name=Invisivle Block
codefile=R1/InvisibleBlock.cs
codetype=SCDObjectDefinitions.R1.InvisibleBlock
[R1/Kamemusi.txt]
name=Kamemusi
xmlfile=R1/Kamemusi.xml
[R1/LogInterior.txt]
name=Log Interior
xmlfile=R1/LogInterior.xml
[R1/LoveHeart.txt]
name=Love Heart
sheet=R1/Objects.gif
frame=-8, -8, 16, 16, 193, 134
hidden=true
[R1/Mosqui.txt]
name=Mosqui
xmlfile=R1/Mosqui.xml
[R1/NoGripArea.txt]
; new Origins Plus obj
name=No Grip Area
codefile=R1/NoGripArea.cs
codetype=SCDObjectDefinitions.R1.NoGripArea
[R1/PaletteAni_A.txt]
name=PaletteAnimation
hidden=true
[R1/PaletteAni_B.txt]
name=PaletteAnimation
hidden=true
[R1/PaletteAni_C.txt]
name=PaletteAnimation
hidden=true
[R1/PaletteAni_D.txt]
name=PaletteAnimation
hidden=true
[R1/PataBata.txt]
name=PataBata
xmlfile=R1/PataBata.xml
[R1/Ramp3D.txt]
name=3D Ramp
codefile=R1/Ramp3D.cs
codetype=SCDObjectDefinitions.R1.Ramp3D
[R1/Rock.txt]
name=Rock
sheet=R1/Objects.gif
frame=-20, -16, 40, 32, 216, 1
[R1/RPlatform.txt]
name=Rise Platform
codefile=R1/Platform.cs
codetype=SCDObjectDefinitions.R1.RPlatform
[R1/SpinTop.txt]
name=Spinning Top
sheet=R1/Objects.gif
frame=-16, -8, 32, 16, 101, 76
[R1/SPlatform.txt]
; generic floating platform that just dips a bit on touch, doesn't need a C# render or anything
name=Small Platform
sheet=R1/Objects.gif
frame=-16, -16, 32, 32, 190, 101
[R1/StarBush.txt]
name=Star Bush
xmlfile=R1/StarBush.xml
[R1/SwingPlat.txt]
name=Swing Platform
codefile=R1/SwingPlat.cs
codetype=SCDObjectDefinitions.R1.SwingPlat
[R1/TagaTaga.txt]
name=TagaTaga
codefile=R1/TagaTaga.cs
codetype=SCDObjectDefinitions.R1.TagaTaga
[R1/TileTriggerH.txt]
name=Tile Trigger H
codefile=R1/TileTrigger.cs
codetype=SCDObjectDefinitions.R1.TileTriggerH
[R1/TileTriggerL.txt]
name=Tile Trigger L
codefile=R1/TileTrigger.cs
codetype=SCDObjectDefinitions.R1.TileTriggerL
[R1/TileTriggerV.txt]
name=Tile Trigger V
codefile=R1/TileTrigger.cs
codetype=SCDObjectDefinitions.R1.TileTriggerV
[R1/TubeSwitch.txt]
name=Tube Switch
xmlfile=R1/TubeSwitch.xml
[R1/TunnelPath.txt]
name=Tunnel Path
codefile=R1/TunnelPath.cs
codetype=SCDObjectDefinitions.R1.TunnelPath
[R1/VPlatform.txt]
name=Vert Platform
codefile=R1/Platform.cs
codetype=SCDObjectDefinitions.R1.VPlatform
[R1/WaterfallSplash.txt]
name=Waterfall Splash
sheet=R1/Objects3.gif
frame=-16, -16, 32, 32, 1, 221
hidden=true
[R1/WaterSplash.txt]
name=Water Splash
sheet=R1/Objects3.gif
frame=-16, -32, 32, 32, 107, 68
[R1/WheelieSpring.txt]
name=Wheelie Spring
codefile=R1/WheelieSpring.cs
codetype=SCDObjectDefinitions.R1.WheelieSpring
