[R3/Amy.txt]
name=Amy Rose
sheet=R3/Objects3.gif
frame=-11, -20, 22, 40, 34, 208
[R3/Blade.txt]
name=Kama Kama Blade
sheet=R3/Objects.gif
frame=-8, -8, 16, 16, 198, 68
hidden=true
[R3/Block.txt]
name=Block
sheet=R3/Objects.gif
frame=-16, -16, 32, 32, 1, 1
[R3/Bomb.txt]
name=Ladybug Bomb
sheet=R3/Objects.gif
frame=-8, -8, 16, 16, 223, 153
hidden=true
[R3/BossBody.txt]
name=Boss Body
xmlfile=R3/BossBody.xml
[R3/Bumper.txt]
name=Bumper
codefile=R3/Bumper.cs
codetype=SCDObjectDefinitions.R3.Bumper
[R3/EBarrier.txt]
name=EBarrier
xmlfile=R3/EBarrier.xml
[R3/Eggman.txt]
name=Eggman
xmlfile=R3/Eggman.xml
[R3/EPlatform.txt]
name=EPlatform
codefile=R3/EPlatform.cs
codetype=SCDObjectDefinitions.R3.EPlatform
[R3/Fireball.txt]
name=Fireball
sheet=R3/Objects.gif
frame=-8, -8, 16, 16, 230, 1
hidden=true
[R3/FlatBumper.txt]
name=Flat Bumper
codefile=R3/FlatBumper.cs
codetype=SCDObjectDefinitions.R3.FlatBumper
[R3/FlipoutBlock.txt]
name=Flipout Block
codefile=R3/FlipoutBlock.cs
codetype=SCDObjectDefinitions.R3.FlipoutBlock
[R3/Flipper.txt]
name=Flipper
xmlfile=R3/Flipper.xml
[R3/Flower.txt]
name=Flower
sheet=R3/Objects2.gif
frame=-4, -8, 8, 16, 246, 25
hidden=true
[R3/FPlatform.txt]
name=F Platform
sheet=R3/Objects.gif
frame=-32, -16, 64, 32, 100, 1
[R3/GateLight.txt]
; technically they could work as deco objects.. but they're not *supposed* to be placed in the scene (i think?)
name=Gate Light
sheet=R3/Objects2.gif
frame=-8, -8, 16, 16, 147, 84
hidden=true
[R3/GlassBumper.txt]
; the Glass Bumper tiles are built into the level, while this object controls their interaction as well as drawing their explosion
; you shouldn't have one without the other, but there's no good way to show that in the editor..
name=Glass Bumper
sheet=R3/Objects3.gif
frame=-16, -16, 32, 32, 66, 1
debug=true
[R3/HPlatform.txt]
name=H Platform
codefile=R3/Platform.cs
codetype=SCDObjectDefinitions.R3.HPlatform
[R3/InvisibleBlock.txt]
; obj is identical to the R1 ver
name=Invisible Block
codefile=R1/InvisibleBlock.cs
codetype=SCDObjectDefinitions.R1.InvisibleBlock
[R3/KamaKama.txt]
name=Kama Kama
xmlfile=R3/KamaKama.xml
[R3/Ladybug.txt]
name=Ladybug
xmlfile=R3/Ladybug.xml
[R3/LoveHeart.txt]
name=Love Heart
sheet=R3/Objects3.gif
frame=-8, -8, 16, 16, 193, 134
hidden=true
[R3/MetalSonic.txt]
name=Metal Sonic
sheet=R3/Objects.gif
frame=-24, -16, 48, 32, 67, 68
[R3/Moth.txt]
name=Moth
xmlfile=R3/Moth.xml
[R3/MothSparkle.txt]
name=Moth Sparkle
sheet=Global/Items.gif
frame=-8, -8, 16, 16, 1, 202
hidden=true
[R3/MovingBlock.txt]
name=Moving Block
codefile=R3/MovingBlock.cs
codetype=SCDObjectDefinitions.R3.MovingBlock
[R3/NoGripArea.txt]
; obj is the same across every scene it's in, let's just pull from the R1 dir
name=No Grip Area
codefile=R1/NoGripArea.cs
codetype=SCDObjectDefinitions.R1.NoGripArea
[R3/OneWayPlat.txt]
name=One Way Platform
codefile=R3/OneWayPlat.cs
codetype=SCDObjectDefinitions.R3.OneWayPlat
[R3/PaletteAni_A.txt]
name=PaletteAnimation
hidden=true
[R3/PaletteAni_C.txt]
name=PaletteAnimation
hidden=true
[R3/PaletteAni_D.txt]
name=PaletteAnimation
hidden=true
[R3/PinballBomb.txt]
name=Pinball Bomb
sheet=R3/Objects2.gif
frame=-12, -12, 24, 24, 232, 0
hidden=true
[R3/Piston.txt]
name=Piston
xmlfile=R3/Piston.xml
[R3/R3Setup.txt]
name=R3 Setup
hidden=true
[R3/RDrumAnimator.txt]
; has no space in present (R32A), but has a space in GF and BF (R32C, R32D)
; we'll go with the latter here
name=R Drum Animator
codefile=R3/RDrumAnimator.cs
codetype=SCDObjectDefinitions.R3.RDrumAnimator
[R3/RecoveryBarrier.txt]
name=Recovery Barrier
sheet=R3/Objects2.gif
frame=-16, -8, 32, 16, 51, 33
[R3/RotatingDrum.txt]
name=Rotating Drum
codefile=R3/RotatingDrum.cs
codetype=SCDObjectDefinitions.R3.RotatingDrum
[R3/RotatingSpikes.txt]
name=Rotating Spikes
codefile=R3/RotatingSpikes.cs
codetype=SCDObjectDefinitions.R3.RotatingSpikes
[R3/RPlatform.txt]
name=R Platform
codefile=R3/Platform.cs
codetype=SCDObjectDefinitions.R3.RPlatform
[R3/ScoreChute.txt]
name=Score Chute
sheet=R3/Objects.gif
frame=-24, -8, 48, 16, 117, 233
[R3/SpikeDebris.txt]
name=Spike Debris
sheet=Global/Items3.gif
frame=-8, -8, 16, 16, 50, 1
hidden=true
[R3/SpinGate.txt]
name=Spin Gate
sheet=R3/Objects2.gif
frame=-16, -8, 32, 16, 18, 50
[R3/TubeSwitch.txt]
name=Tube Switch
xmlfile=R3/TubeSwitch.xml
[R3/VPlatform.txt]
name=V Platform
codefile=R3/Platform.cs
codetype=SCDObjectDefinitions.R3.VPlatform
