[R5/BGSwapper.txt]
name=BG Swapper
xmlfile=R5/BGSwapper.xml
[R5/BombCarrier.txt]
name=Bomb Carrier
sheet=R5/Objects2.gif
frame=-16, -12, 32, 24, 33, 215
[R5/BossBackPanel.txt]
name=Boss Back Panel
xmlfile=R5/BossBackPanel.xml
[R5/BossBomb.txt]
name=Boss Bomb
sheet=R5/Objects2.gif
frame=-12, -12, 24, 24, 75, 113
[R5/BossExplosion.txt]
name=Boss Explosion
sheet=Global/Items2.gif
frame=-16, -8, 32, 16, 1, 1
hidden=true
[R5/BossPlatform.txt]
name=Boss Platform
xmlfile=R5/BossPlatform.xml
[R5/BossSpark.txt]
name=Boss Spark
sheet=R5/Objects2.gif
frame=-2, -4, 16, 8, 131, 155
hidden=true
[R5/BossSpikes.txt]
name=Boss Spikes
codefile=R5/Generic.cs
codetype=SCDObjectDefinitions.R5.BossSpikes
[R5/BossTop.txt]
name=Boss Top
xmlfile=R5/BossTop.xml
[R5/BreakWall.txt]
name=Breakable Wall
codefile=R5/Generic.cs
codetype=SCDObjectDefinitions.R5.BreakWall
[R5/Bridge.txt]
name=Bridge
codefile=R5/Bridge.cs
codetype=SCDObjectDefinitions.R5.Bridge
[R5/CBSwitch.txt]
name=CBSwitch
codefile=R5/Generic.cs
codetype=SCDObjectDefinitions.R5.CBSwitch
[R5/ConveyorBelt.txt]
; has a space in R52B (Quartz 2 Past) and nowhere else, let's go with space since it looks neater
name=Conveyor Belt
hidden=true
[R5/CPlatform.txt]
name=CPlatform
codefile=R5/CPlatform.cs
codetype=SCDObjectDefinitions.R5.CPlatform
[R5/DipPlatform.txt]
name=Dipping Platform
codefile=R5/GenericPlatform.cs
codetype=SCDObjectDefinitions.R5.Platform
[R5/DoublePlatform.txt]
name=Double Platform
codefile=R5/DoublePlatform.cs
codetype=SCDObjectDefinitions.R5.DoublePlatform
[R5/DropRock.txt]
name=Drop Rock
codefile=R5/DropRock.cs
codetype=SCDObjectDefinitions.R5.DropRock
[R5/Eggman.txt]
name=Eggman
sheet=R5/Objects2.gif
frame=-24, -24, 40, 56, 174, 181
[R5/FadeMusic.txt]
name=Fade Music
hidden=true
[R5/FallPlatform.txt]
name=Falling Platform
codefile=R5/GenericPlatform.cs
codetype=SCDObjectDefinitions.R5.FPlatform
[R5/Flower.txt]
name=Flower
sheet=R5/Objects.gif
frame=-4, -8, 8, 16, 99, 51
hidden=true
[R5/ForegroundPiece.txt]
name=Foreground Piece
codefile=R5/ForegroundPiece.cs
codetype=SCDObjectDefinitions.R5.ForegroundPiece
[R5/HPlatformLarge.txt]
name=HPlatform Large
codefile=R5/HPlatform.cs
codetype=SCDObjectDefinitions.R5.HPlatformLarge
[R5/HPlatformMedium1.txt]
name=HPlatformMedium1
codefile=R5/HPlatform.cs
codetype=SCDObjectDefinitions.R5.HPlatformMedium1
[R5/HPlatformMedium2.txt]
name=HPlatformMedium2
codefile=R5/HPlatform.cs
codetype=SCDObjectDefinitions.R5.HPlatformMedium2
[R5/HPlatformSmall.txt]
name=HPlatform Small
codefile=R5/HPlatform.cs
codetype=SCDObjectDefinitions.R5.HPlatformSmall
[R5/Kemusi.txt]
name=Kemusi
xmlfile=R5/Kemusi.xml
[R5/KumoKumo.txt]
name=Kumo Kumo
xmlfile=R5/KumoKumo.xml
[R5/KWeb.txt]
name=Kumo Kumo Web
sheet=R5/Objects.gif
frame=-12, -8, 24, 16, 69, 1
hidden=true
[R5/NoroNoro.txt]
name=Noro Noro
xmlfile=R5/NoroNoro.xml
[R5/R5AGlowEffect.txt]
name=Glow Effect
hidden=true
[R5/R5DEffect.txt]
name=BG Effect
hidden=true
[R5/RisePlatform.txt]
; prop val's not used, even if it is set
name=Rise Platform
codefile=R5/RisePlatform.cs
codetype=SCDObjectDefinitions.R5.RisePlatform
[R5/RisePlatform2.txt]
name=Rise Platform 2
codefile=R5/RisePlatform.cs
codetype=SCDObjectDefinitions.R5.RisePlatform2
[R5/RotatingLog.txt]
name=Rotating Log
codefile=R5/RotatingLog.cs
codetype=SCDObjectDefinitions.R5.RotatingLog
[R5/RPlatform.txt]
name=R Platform
codefile=R5/RPlatform.cs
codetype=SCDObjectDefinitions.R5.RPlatform
[R5/Sasuri.txt]
name=Sasuri
xmlfile=R5/Sasuri.xml
[R5/SBullet.txt]
name=Sasuri Bullet
sheet=R5/Objects.gif
frame=-8, -8, 16, 16, 67, 27
hidden=true
[R5/Stalactite.txt]
name=Stalactite
codefile=R5/Generic.cs
codetype=SCDObjectDefinitions.R5.Stalactite
[R5/StaticPlatform.txt]
name=Static Platform
codefile=R5/GenericPlatform.cs
codetype=SCDObjectDefinitions.R5.Platform
[R5/StaticRock.txt]
name=Static Rock
codefile=R5/StaticRock.cs
codetype=SCDObjectDefinitions.R5.StaticRock
[R5/TubeSwitch.txt]
name=Tube Switch
xmlfile=R5/TubeSwitch.xml
[R5/TunnelPath1.txt]
name=Tunnel Path 1
codefile=R5/TunnelPath.cs
codetype=SCDObjectDefinitions.R5.TunnelPath1
[R5/TunnelPath2.txt]
name=Tunnel Path 2
codefile=R5/TunnelPath.cs
codetype=SCDObjectDefinitions.R5.TunnelPath2
[R5/TunnelPath3.txt]
name=Tunnel Path 3
codefile=R5/TunnelPath.cs
codetype=SCDObjectDefinitions.R5.TunnelPath3
[R5/TunnelPath4.txt]
name=Tunnel Path 4
codefile=R5/TunnelPath.cs
codetype=SCDObjectDefinitions.R5.TunnelPath4
[R5/TunnelPath5.txt]
name=Tunnel Path 5
codefile=R5/TunnelPath.cs
codetype=SCDObjectDefinitions.R5.TunnelPath5
[R5/VPlatformLarge.txt]
name=VPlatform Large
codefile=R5/VPlatform.cs
codetype=SCDObjectDefinitions.R5.VPlatformLarge
[R5/VPlatformMedium.txt]
name=VPlatform Medium
codefile=R5/VPlatform.cs
codetype=SCDObjectDefinitions.R5.VPlatformMedium
[R5/VPlatformSmall.txt]
name=VPlatform Small
codefile=R5/VPlatform.cs
codetype=SCDObjectDefinitions.R5.VPlatformSmall
