[R6/AngelRing.txt]
name=Angel Ring
codefile=R6/AngelRing.cs
codetype=SCDObjectDefinitions.R6.AngelRing
[R6/BataPyon.txt]
name=Bata Pyon
xmlfile=R6/BataPyon.xml
[R6/BigPlatform.txt]
name=Big Platform
codefile=R6/BigPlatform.cs
codetype=SCDObjectDefinitions.R6.BigPlatform
[R6/Bomb.txt]
name=Semi Bomb
sheet=R6/Objects.gif
frame=-8, -8, 16, 16, 43, 67
hidden=true
[R6/BossBarrier.txt]
name=Boss Barrier
xmlfile=R6/BossBarrier.xml
[R6/BossBarrier2.txt]
name=Boss Barrier 2
xmlfile=R6/BossBarrier2.xml
[R6/BossCamera.txt]
name=Boss Camera
hidden=true
[R6/BossElectrode.txt]
name=Boss Electrode
xmlfile=R6/BossElectrode.xml
[R6/BossFloorControl.txt]
name=Floor Control
hidden=true
[R6/BossPlatform.txt]
; well yeah technically we should have a time period check for this obj but it's hidden anyways, so
name=Boss Platform
sheet=R6/Objects3.gif
frame=-16, -16, 32, 32, 223, 200
hidden=true
[R6/BossSpike.txt]
name=Boss Spike
sheet=R6/Objects2.gif
frame=-4, -12, 8, 24, 228, 1
hidden=true
[R6/BouncePlatform.txt]
name=Bounce Platform
sheet=R6/Objects.gif
frame=-32, -16, 64, 32, 132, 43
[R6/Climber.txt]
name=Climber
xmlfile=R6/Climber.xml
[R6/DestroyedMobile.txt]
name=Destroyed Mobile
sheet=R6/Objects2.gif
frame=-64, 0, 128, 32, 66, 98
hidden=true
[R6/EggmanEscape.txt]
name=Eggman Escape
sheet=R6/Objects2.gif
frame=-32, -25, 64, 48, 1, 170
[R6/EggmanMobile.txt]
name=Eggman Mobile
xmlfile=R6/EggmanMobile.xml
[R6/EggmanStatue.txt]
name=Eggman Statue
sheet=R6/Objects3.gif
frame=-20, -28, 40, 56, 81, 181
[R6/ElectricArc.txt]
name=Electric Arc
sheet=R6/Objects3.gif
frame=-176, -8, 16, 16, 1, 1
hidden=true
[R6/ElectricWeb.txt]
name=Electric Web
xmlfile=R6/ElectricWeb.xml
[R6/FadeScreen.txt]
name=Fade Screen
hidden=true
[R6/FlipDoor.txt]
name=Flip Door
xmlfile=R6/FlipDoor.xml
[R6/FloorRubble.txt]
name=Floor Rubble
sheet=R6/Objects2.gif
frame=-8, -8, 16, 16, 165, 191
hidden=true
[R6/Flower.txt]
name=Flower
sheet=R6/Objects3.gif
frame=-4, -8, 8, 16, 238, 1
hidden=true
[R6/FreezeJet.txt]
name=Freeze Jet
codefile=R6/FreezeJet.cs
codetype=SCDObjectDefinitions.R6.FreezeJet
[R6/HangingTrigger.txt]
name=Hanging Trigger
codefile=R6/HangingTrigger.cs
codetype=SCDObjectDefinitions.R6.HangingTrigger
[R6/HPlatform.txt]
name=H Platform
codefile=R6/Platform.cs
codetype=SCDObjectDefinitions.R6.HPlatform
[R6/HSpinPlatform.txt]
name=H Spin Platform
codefile=R6/Platform.cs
codetype=SCDObjectDefinitions.R6.HSpinPlatform
[R6/IceBlock.txt]
name=Ice Block
sheet=R6/Objects.gif
frame=-24, -24, 48, 48, 34, 18
hidden=true
[R6/InvisibleBarrier.txt]
; new origins plus obj
; in ANR61A, it's called [Invisible Barrie] (sic)
; in every other stage (so every other AN act 1 time period), it's called [R6 Barrier]
; even if it doesn't match the script name.. let's go with the latter instead, at least it's not cut off lol
name=R6 Barrier
codefile=R6/InvisibleBarrier.cs
codetype=SCDObjectDefinitions.R6.InvisibleBarrier
[R6/InvisibleBlock.txt]
; obj is identical to the R1 ver
name=Invisible Block
codefile=R1/InvisibleBlock.cs
codetype=SCDObjectDefinitions.R1.InvisibleBlock
[R6/InvisibleBlockNK.txt]
; (yeah the file is in the r1 folder, but that's cause it's based on the R1 invis block class, so..)
name=Invisible Block
codefile=R1/InvisibleBlock.cs
codetype=SCDObjectDefinitions.R6.InvisibleBlockNK
[R6/Launcher.txt]
name=Launcher
sheet=R6/Objects.gif
frame=-28, -28, 56, 32, 83, 1
[R6/Minomusi.txt]
name=Minomusi
codefile=R6/Minomusi.cs
codetype=SCDObjectDefinitions.R6.Minomusi
[R6/MovingBlocks.txt]
name=Moving Blocks
codefile=R6/MovingBlocks.cs
codetype=SCDObjectDefinitions.R6.MovingBlocks
[R6/MovingBlocks2.txt]
name=Moving Blocks
codefile=R6/MovingBlocks2.cs
codetype=SCDObjectDefinitions.R6.MovingBlocks2
[R6/NoGripArea.txt]
; obj is the same across every scene it's in, let's just pull from the R1 dir
name=No Grip Area
codefile=R1/NoGripArea.cs
codetype=SCDObjectDefinitions.R1.NoGripArea
[R6/PohBee.txt]
name=Poh Bee
xmlfile=R6/PohBee.xml
[R6/PohBeeBullet.txt]
name=Poh Bee Bullet
sheet=R6/Objects.gif
frame=-8, -8, 16, 16, 197, 68
hidden=true
[R6/PoleTrigger.txt]
name=Pole Trigger
codefile=R6/PoleTrigger.cs
codetype=SCDObjectDefinitions.R6.PoleTrigger
[R6/PushButton.txt]
name=Push Button
sheet=R6/Objects.gif
frame=-16, -8, 32, 16, 140, 1
[R6/R6BossCSetup.txt]
name=R6 Setup
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
hidden=true
[R6/R6BossDSetup.txt]
name=R6 Setup
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
hidden=true
[R6/R6BounceFloor.txt]
; new origins plus obj
name=R6 BounceFloor
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
hidden=true
[R6/R6CSetup.txt]
name=R6 Setup
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
hidden=true
[R6/R6DSetup.txt]
name=R6 Setup
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
hidden=true
[R6/R6Setup.txt]
name=R6 Setup
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
hidden=true
[R6/RotatingSpikes.txt]
name=Rotating Spikes
codefile=R6/RotatingSpikes.cs
codetype=SCDObjectDefinitions.R6.RotatingSpikes
[R6/Semi.txt]
name=Semi
xmlfile=R6/Semi.xml
[R6/StatueBomb.txt]
name=Statue Bomb
sheet=R6/Objects.gif
frame=-8, -8, 16, 16, 43, 67
hidden=true
[R6/SteamCloud.txt]
name=Steam Cloud
sheet=R6/Objects2.gif
frame=-12, -12, 24, 24, 228, 26
hidden=true
[R6/TileSwapper.txt]
name=Tile Swapper
codefile=R6/TileSwapper.cs
codetype=SCDObjectDefinitions.R6.TileSwapper
[R6/TubeSwitch.txt]
; okay, so this is an interesting one..
; in act 1, it's called [Tube Switch]
; in act 2, however, it's [Tube SW]
; in the script itself.. the object uses TypeName[Tube SW] to initialize itself, so going with the act 1 name
;  actually leads to the object behaving incorrectly (every hitbox is 1x1 instead of the expected 16x16)
; so.. we're going to go with the latter name here obvi, but just felt like it was worth noting all this-
name=Tube SW
codefile=R6/TubeSwitch.cs
codetype=SCDObjectDefinitions.R6.TubeSwitch
[R6/TubeTrapDoor.txt]
name=Tube Trap Door
codefile=R6/TubeTrapDoor.cs
codetype=SCDObjectDefinitions.R6.TubeTrapDoor
[R6/TunnelPath1.txt]
name=Tunnel Path 1
codefile=R6/TunnelPath.cs
codetype=SCDObjectDefinitions.R6.TunnelPath1
[R6/TunnelPath2.txt]
name=Tunnel Path 2
codefile=R6/TunnelPath.cs
codetype=SCDObjectDefinitions.R6.TunnelPath2
[R6/TunnelPath3.txt]
name=Tunnel Path 3
codefile=R6/TunnelPath.cs
codetype=SCDObjectDefinitions.R6.TunnelPath3
[R6/TunnelPath4.txt]
name=Tunnel Path 4
codefile=R6/TunnelPath.cs
codetype=SCDObjectDefinitions.R6.TunnelPath4
[R6/TunnelPath5.txt]
name=Tunnel Path 5
codefile=R6/TunnelPath.cs
codetype=SCDObjectDefinitions.R6.TunnelPath5
[R6/TunnelPath6.txt]
name=Tunnel Path 6
codefile=R6/TunnelPath.cs
codetype=SCDObjectDefinitions.R6.TunnelPath6
[R6/TunnelPath7.txt]
name=Tunnel Path 7
codefile=R6/TunnelPath.cs
codetype=SCDObjectDefinitions.R6.TunnelPath7
[R6/TunnelPath8.txt]
name=Tunnel Path 8
codefile=R6/TunnelPath.cs
codetype=SCDObjectDefinitions.R6.TunnelPath8
[R6/TunnelPath9.txt]
name=Tunnel Path 9
codefile=R6/TunnelPath.cs
codetype=SCDObjectDefinitions.R6.TunnelPath9
[R6/TunnelPath10.txt]
name=Tunnel Path 10
codefile=R6/TunnelPath.cs
codetype=SCDObjectDefinitions.R6.TunnelPath10
[R6/VerticalDoor.txt]
name=Vertical Door
xmlfile=R6/VerticalDoor.xml
[R6/VPlatform.txt]
name=V Platform
codefile=R6/Platform.cs
codetype=SCDObjectDefinitions.R6.VPlatform
[R6/VSpinPlatform.txt]
name=V Spin Platform
codefile=R6/Platform.cs
codetype=SCDObjectDefinitions.R6.VSpinPlatform
