[Global/ActFinish.txt]
name=Act Finish
sheet=Global/Display.gif
frame=0, 0, 95, 16, 49, 205
hidden=true
[Global/AnimalPrison.txt]
name=Animal Prison
xmlfile=Global/AnimalPrison.xml
[Global/BlueShield.txt]
name=Blue Shield
sheet=Global/Items2.gif
frame=-24, -24, 48, 48, 109, 196
hidden=true
[Global/BlueShield2.txt]
name=Blue Shield 2
sheet=Global/Items.gif
frame=-16, -16, 32, 32, 18, 34
hidden=true
[Global/BonusPoints.txt]
name=Bonus Points
xmlfile=Global/BonusPoints.xml
[Global/BrokenMonitor.txt]
name=Broken Monitor
sheet=Global/Items.gif
frame=-16, 0, 32, 16, 51, 166
hidden=true
[Global/BubbleShield.txt]
name=Bubble Shield
sheet=Global/Items3.gif
frame=-24, -24, 48, 48, 1, 1
hidden=true
[Global/DeathEvent.txt]
name=Death Event
sheet=Global/Display.gif
frame=0, 0, 64, 16, 1, 239
hidden=true
[Global/DebugMode.txt]
name=Debug Mode
sheet=Global/Display.gif
frame=-8, -8, 16, 16, 188, 239
hidden=true
[Global/DustPuff.txt]
name=Dust Puff
sheet=Global/Items.gif
frame=-7, -11, 13, 14, 51, 183
hidden=true
[Global/Explosion.txt]
name=Explosion
sheet=Global/Items2.gif
frame=-16, -16, 32, 32, 1, 84
hidden=true
[Global/FireShield.txt]
name=Fire Shield
sheet=Global/Items3.gif
frame=-16, 9, 37, 15, 131, 52
hidden=true
[Global/Goggles.txt]
; intentionally left placeable in contrast to the other shields, it's a feature of this object where
; it can be placed into a scene and will make the player start with goggles
name=Goggles
sheet=Global/Items.gif
frame=-4, -12, 12, 9, 118, 71
[Global/HUD.txt]
name=HUD
sheet=Global/Display.gif
frame=0, 0, 39, 43, 1, 1
debug=true
[Global/InstaShield.txt]
name=Insta Shield
sheet=Global/Items3.gif
frame=-16, -24, 40, 40, 173, 214
hidden=true
[Global/Invincibility.txt]
name=Invincibility
sheet=Global/Items.gif
frame=-24, -24, 48, 48, 207, 1
hidden=true
[Global/Invincibility2.txt]
name=Invincibility 2
sheet=Global/Items.gif
frame=-15, -15, 31, 31, 18, 169
hidden=true
[Global/InvisibleBlock.txt]
name=Invisible Block
codefile=Global/InvisibleBlock.cs
codetype=S1ObjectDefinitions.Global.InvisibleBlock
[Global/LampPost.txt]
; prop val is unused, even if it's set
; (checkpoints are automatically sorted via entityPos instead)
name=Lamp Post
sheet=Global/Items.gif
frame=-8, -44, 16, 64, 1, 137
[Global/LightningShield.txt]
name=LightningShield
sheet=Global/Items3.gif
frame=-8, -24, 31, 48, 191, 1
hidden=true
[Global/LightningSpark.txt]
name=Lightning Spark
sheet=Global/Items3.gif
frame=-8, -8, 16, 16, 157, 84
hidden=true
[Global/LoseRing.txt]
name=Lose Ring
sheet=Global/Items.gif
frame=-8, -8, 16, 16, 1, 1
hidden=true
[Global/Monitor.txt]
name=Monitor
xmlfile=Global/Monitor.xml
[Global/MusicEvent.txt]
name=Music Event
hidden=true
[Global/ObjectScore.txt]
name=Object Score
sheet=Global/Items.gif
frame=-6, 0, 14, 8, 193, 226
hidden=true
[Global/PSwitch_H.txt]
name=Plane Sw H
codefile=Global/PSwitch_H.cs
codetype=S1ObjectDefinitions.Global.PSwitch_H
[Global/PSwitch_Loop.txt]
name=Plane Sw L
codefile=Global/PSwitch_Loop.cs
codetype=S1ObjectDefinitions.Global.PSwitch_Loop
[Global/PSwitch_V.txt]
name=Plane Sw V
codefile=Global/PSwitch_V.cs
codetype=S1ObjectDefinitions.Global.PSwitch_V
[Global/RedSpring.txt]
name=Red Spring
codefile=Global/RedSpring.cs
codetype=S1ObjectDefinitions.Global.RedSpring
[Global/Ring.txt]
name=Ring
xmlfile=Global/Ring.xml
[Global/RingSparkle.txt]
; even if it's placed a few times in MZ1 (???) it's still hidden here because
; it really shouldn't be in a scene at all
name=Ring Sparkle
sheet=Global/Items.gif
frame=-8, -8, 16, 16, 1, 202
hidden=true
[Global/SignPost.txt]
name=Sign Post
xmlfile=Global/SignPost.xml
[Global/SmokePuff.txt]
name=Smoke Puff
sheet=Global/Items2.gif
frame=-16, -16, 32, 32, 1, 18
hidden=true
[Global/SpecialRing.txt]
name=Special Ring
sheet=Global/Items2.gif
frame=-32, -32, 64, 64, 83, 1
[Global/Spikes.txt]
name=Spikes
codefile=Global/Spikes.cs
codetype=S1ObjectDefinitions.Global.Spikes
[Global/StageSetup.txt]
name=Stage Setup
hidden=true
debug=true
[Global/SuperSpark.txt]
name=Super Spark
sheet=Global/Items3.gif
frame=-8, -8, 16, 16, 168, 158
hidden=true
[Global/TailsStuck.txt]
name=Tails Stuck
codefile=Global/TailsStuck.cs
codetype=S1ObjectDefinitions.Global.TailsStuck
[Global/TitleCard.txt]
; *should* be placed in regular stages, but should *not* be in special stages
; setting up a whole C# render just for that would be a bit too much, this note is suffice enough hopefully
name=Title Card
xmlfile=Global/TitleCard.xml
[Global/YBoundAdjust.txt]
name=Y Bound Adjust
codefile=Global/YBoundAdjust.cs
codetype=S1ObjectDefinitions.Global.YBoundAdjust
[Global/YellowSpring.txt]
name=Yellow Spring
codefile=Global/YellowSpring.cs
codetype=S1ObjectDefinitions.Global.YellowSpring
