[Mission/BallHog2.txt]
name=Ball Hog
codefile=Enemies/BallHog.cs
codetype=S1ObjectDefinitions.Enemies.BallHog
[Mission/BallHogBomb2.txt]
name=Ball Hog Bomb
codefile=Enemies/Generic.cs
codetype=S1ObjectDefinitions.Enemies.BallHogBomb
[Mission/Batbrain2.txt]
name=Batbrain
codefile=Enemies/Generic.cs
codetype=S1ObjectDefinitions.Enemies.Batbrain
[Mission/Boss3Safty.txt]
name=Safty
codefile=Mission/Boss3Safty.cs
codetype=S1ObjectDefinitions.Mission.Safty
[Mission/Caterkiller2.txt]
name=Caterkiller
codefile=Enemies/Caterkiller.cs
codetype=S1ObjectDefinitions.Enemies.Caterkiller
[Mission/EggmanSignPost.txt]
name=EggmanSignPost
sheet=Global/Items2.gif
frame=-24, -16, 48, 48, 34, 182
debug=true
[Mission/FallSignPost.txt]
name=FallSignPost
sheet=Global/Items2.gif
frame=-24, -16, 48, 48, 34, 182
debug=true
[Mission/Gliding.txt]
name=Gliding
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
debug=true
[Mission/ImmediateDeath.txt]
name=ImmediateDeath
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
debug=true
[Mission/MissionAreaBL.txt]
name=MissionAreaBL
codefile=Mission/MissionArea.cs
codetype=S1ObjectDefinitions.Mission.MissionAreaBL
[Mission/MissionAreaTR.txt]
name=MissionAreaTR
codefile=Mission/MissionArea.cs
codetype=S1ObjectDefinitions.Mission.MissionAreaTR
[Mission/MissionBlock.txt]
name=MissionBlock
codefile=Mission/MissionBlock.cs
codetype=S1ObjectDefinitions.Mission.MissionBlock
[Mission/MissionWater.txt]
name=MissionWater
sheet=LZ/Objects2.gif
frame=0, -8, 256, 16, 0, 129
[Mission/Motobug2.txt]
name=Motobug
codefile=Enemies/Motobug.cs
codetype=S1ObjectDefinitions.Enemies.Motobug
[Mission/ReviveBatbrain.txt]
name=Batbrain
codefile=Enemies/Generic.cs
codetype=S1ObjectDefinitions.Enemies.Batbrain
[Mission/ReviveCaterkiller.txt]
name=Caterkiller
codefile=Enemies/Caterkiller.cs
codetype=S1ObjectDefinitions.Enemies.Caterkiller
[Mission/ReviveCrabmeat.txt]
name=Crabmeat
codefile=Enemies/Crabmeat.cs
codetype=S1ObjectDefinitions.Enemies.Crabmeat
[Mission/ReviveEnemy.txt]
; between the SYZ and DLC MZ missions, they use a space in one and not the other, but
; let's just go with the space here
name=Revive Enemy
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
debug=true
[Mission/ReviveMotobug2.txt]
; blank script :(
name=Revive Motobug
hidden=true
[Mission/RingReset.txt]
name=RingReset
sheet=Global/Items.gif
frame=-8, -8, 16, 16, 1, 1
debug=true
[Mission/SetRingCount.txt]
name=SetRingCount
codefile=Mission/SetRingCount.cs
codetype=S1ObjectDefinitions.Mission.SetRingCount
[Mission/SignPost2.txt]
name=SignPost2
codefile=Mission/SignPost2.cs
codetype=S1ObjectDefinitions.Mission.SignPost2
[Mission/WatchLoseRing.txt]
name=WatchLoseRing
sheet=Global/Items.gif
frame=-8, -8, 16, 16, 1, 1
debug=true
