[Players/PlayerObject.txt]
name=Player Object
anim=Sonic.ani:0:0
[Players/Player2Object.txt]
; even if it's placed a couple of times in MZ1 (???) we still keep it hidden here
; because really you have no reason to put one in a scene
name=Player 2 Object
anim=Tails.ani:0:0
hidden=true
[Players/TailsObject.txt]
name=Tails Object
anim=Tails.ani:0:0
hidden=true
