EXEFile=Sonic2Absolute.exe
DataFile=Absolute.rsdk
;BaseMod=Sonic 2 Absolute ; Not necessary yet, just here for if/when the next S2A update drops and they switch to being a mod instead of the Easy Setup thing
RSDKVer=v4
