[LZ/AirBubble.txt]
name=Air Bubble
sheet=LZ/Objects.gif
frame=-16, -16, 32, 32, 86, 18
hidden=true
[LZ/AirBubbler.txt]
name=Air Bubbler
xmlfile=LZ/AirBubbler.xml
[LZ/BeltActivation.txt]
name=Belt Activation
codefile=LZ/BeltActivation.cs
codetype=S1ObjectDefinitions.LZ.BeltActivation
[LZ/BeltPlatform.txt]
name=Belt Platform
codefile=LZ/BeltPlatform.cs
codetype=S1ObjectDefinitions.LZ.BeltPlatform
[LZ/Cork.txt]
name=Cork
sheet=LZ/Objects.gif
frame=-16, -16, 32, 32, 1, 51
[LZ/CorkActivation.txt]
name=Cork Activation
codefile=LZ/BeltActivation.cs
codetype=S1ObjectDefinitions.LZ.CorkActivation
[LZ/CountdownBubble.txt]
name=Countdown Bubble
sheet=LZ/Objects.gif
frame=-8, -10, 16, 20, 187, 1
hidden=true
[LZ/CurrentTunnel.txt]
; yeah S1F adds its own debug vis, but let's stay consistent between 2013 and S1F in the editor when possible (and this ver gives more info so it's more useful imo)
name=Current Tunnel
codefile=LZ/CurrentTunnel.cs
codetype=S1ObjectDefinitions.LZ.CurrentTunnel
[LZ/Door.txt]
name=Door
xmlfile=LZ/Door.xml
[LZ/DoorFlapping.txt]
name=Flapping Door
xmlfile=LZ/DoorFlapping.xml
[LZ/Eggman.txt]
name=Eggman
codefile=LZ/Eggman.cs
codetype=S1ObjectDefinitions.LZ.Eggman
[LZ/FallingBlock.txt]
name=Falling Block
sheet=LZ/Objects.gif
frame=-16, -16, 32, 32, 84, 223
[LZ/Gargoyle.txt]
name=Gargoyle
codefile=LZ/Gargoyle.cs
codetype=S1ObjectDefinitions.LZ.Gargoyle
[LZ/GargoyleShot.txt]
name=Gargoyle Shot
sheet=LZ/Objects.gif
frame=-8, -3, 15, 6, 127, 124
hidden=true
[LZ/GrabBar.txt]
name=Grab Bar
xmlfile=LZ/GrabBar.xml
[LZ/HarpoonHoriz.txt]
name=Harpoon H
codefile=LZ/HarpoonHoriz.cs
codetype=S1ObjectDefinitions.LZ.HarpoonHoriz
[LZ/HarpoonVert.txt]
name=Harpoon V
codefile=LZ/HarpoonVert.cs
codetype=S1ObjectDefinitions.LZ.HarpoonVert
[LZ/HorizontalDoor.txt]
name=Door Horizontal
codefile=LZ/HorizontalDoor.cs
codetype=S1ObjectDefinitions.LZ.HorizontalDoor
[LZ/LZSetup.txt]
name=LZ Setup
hidden=true
[LZ/Push Block.txt]
name=Push Block
xmlfile=LZ/PushBlock.xml
[LZ/PushButton.txt]
name=Push Button
xmlfile=LZ/PushButton.xml
[LZ/RisingPlatform.txt]
name=Rising Platform
codefile=LZ/RisingPlatform.cs
codetype=S1ObjectDefinitions.LZ.RisingPlatform
[LZ/RotatingSpike.txt]
name=Rotating Spike
codefile=LZ/RotatingSpike.cs
codetype=S1FObjectDefinitions.LZ.RotatingSpike
[LZ/SBZ3Exit.txt]
name=SBZ3 Exit
sheet=Global/Display.gif
frame=-8, -8, 16, 16, 239, 239
debug=true
[LZ/SBZ3Fall.txt]
name=SBZ3 Fall
sheet=Global/Display.gif
frame=-8, -8, 16, 16, 239, 239
debug=true
[LZ/SecretPlatform.txt]
name=Moving Block
sheet=LZ/Objects.gif
frame=-16, -8, 32, 16, 1, 1
[LZ/ShardKey.txt]
; for now it's hidden, but they'll (hopefully-) unhardcode its spawning later down the line-
name=Shard Key
sheet=LZ/Objects3.gif
frame=-3, -7, 6, 14, 1, 180
hidden=true
[LZ/SlidingFloor.txt]
name=Sliding Floor
codefile=LZ/SlidingFloor.cs
codetype=S1ObjectDefinitions.LZ.SlidingFloor
[LZ/SolidBlock.txt]
name=Solid Block
sheet=LZ/Objects.gif
frame=-16, -16, 32, 32, 1, 18
[LZ/TouchBlock.txt]
name=Touch Block
sheet=LZ/Objects.gif
frame=-16, -16, 32, 32, 84, 223
[LZ/VerticalWrap.txt]
name=Vertical Wrap
sheet=Global/Display.gif
frame=-8, -8, 16, 16, 239, 239
debug=true
[LZ/Water.txt]
name=Water
sheet=LZ/Objects2.gif
frame=0, -8, 256, 16, 0, 129
[LZ/Waterfall.txt]
name=Waterfall
xmlfile=LZ/Waterfall.xml
[LZ/WaterPlane.txt]
name=Water Plane
codefile=LZ/WaterPlane.cs
codetype=S1FObjectDefinitions.LZ.WaterPlane
[LZ/WaterSplash.txt]
name=Water Splash
sheet=LZ/Objects.gif
frame=-16, -32, 32, 32, 190, 43
hidden=true
[LZ/Wheel.txt]
name=Wheel
sheet=LZ/Objects.gif
frame=-16, -16, 32, 32, 223, 22
