[MainMenu/Arcade.txt]
name=Arcade
sheet=Menus/ArcadeMode.gif
frame=-55, -74, 103, 148, 1, 363
[MainMenu/Extras.txt]
name=Extras Menu
hidden=true
[MainMenu/GolfMenu.txt]
name=Golf Menu
sheet=Menus/Golf.gif
frame=0, 0, 177, 21, 1, 316
[MainMenu/Main.txt]
name=Main Menu
; threatening face
sheet=Menus/MonIcon.gif
frame=0, -41, 80, 83, 455, 1
[MainMenu/Modes.txt]
name=Game Modes Menu
hidden=true
[MainMenu/ModMenu.txt]
name=Mod Menu
hidden=true
[MainMenu/MonIcons.txt]
name=Menu Monitor Icon
hidden=true
[MainMenu/Options.txt]
name=Options Menu
hidden=true
[MainMenu/Test.txt]
name=Test
hidden=true
[MainMenu/Text.txt]
name=Text Render
hidden=true
