[MBZ/AirBubble.txt]
name=Air Bubble
sheet=LZ/Objects.gif
frame=-2, -2, 4, 4, 61, 1
hidden=true
[MBZ/BossBarrier.txt]
name=Boss Barrier
xmlfile=MBZ/BossBarrier.xml
[MBZ/BossBlock.txt]
name=Boss Block
sheet=MBZ/Objects.gif
frame=-16, -16, 32, 32, 76, 363
[MBZ/BossChain.txt]
name=Boss Chain
sheet=GHZ/Objects.gif
frame=-8, -8, 16, 16, 101, 1
hidden=true
[MBZ/BossFireball.txt]
name=Boss Fireball
sheet=MBZ/Objects.gif
frame=-7, -23, 15, 31, 158, 429
hidden=true
[MBZ/BossLights.txt]
name=Boss Lights
sheet=Global/Eggman.gif
frame=-8, -5, 16, 13, 196, 24
hidden=true
[MBZ/Buzzsaw.txt]
; the mbz script is a copy of the sbz script, same sheet and all, so
name=Buzzsaw
codefile=SBZ/Buzzsaw.cs
codetype=S1ObjectDefinitions.SBZ.Buzzsaw
[MBZ/CFloor.txt]
name=C Floor
xmlfile=MBZ/CFloor.xml
[MBZ/Cloud.txt]
sheet=MBZ/Objects.gif
frame=-31, -13, 62, 26, 2, 393
[MBZ/ConveyorWheel.txt]
name=Conveyor Wheel
codefile=MBZ/ConveyorWheel.cs
codetype=S1FObjectDefinitions.MBZ.ConveyorWheel
[MBZ/Crust.txt]
name=Crust
codefile=MBZ/Crust.cs
codetype=S1FObjectDefinitions.MBZ.Crust
[MBZ/FZEggman.txt]
name=FZ Eggman
sheet=SBZ/Objects.gif
frame=-22, -23, 38, 51, 1, 209
[MBZ/FZEggmobile.txt]
name=FZ Eggmobile
xmlfile=SBZ/Eggmobile.xml
[MBZ/FZPiston.txt]
name=FZ Piston
sheet=MBZ/Objects2.gif
frame=-32, -96, 64, 216, 256, 1
[MBZ/Gargoyle.txt]
name=Gargoyle
codefile=MBZ/Gargoyle.cs
codetype=S1FObjectDefinitions.MBZ.Gargoyle
[MBZ/GargoyleShot.txt]
name=Gargoyle Shot
sheet=MBZ/Objects.gif
frame=-4, -5, 11, 9, 211, 145
hidden=true
[MBZ/GHZEggman.txt]
name=GHZ Eggman
sheet=Global/Eggman.gif
frame=-28, -32, 64, 56, 1, 1
[MBZ/GHZPlatform.txt]
name=GHZ Platform
sheet=MBZ/Objects.gif
frame=-32, -8, 64, 14, 170, 295
[MBZ/HarpoonHoriz.txt]
name=Harpoon H
codefile=MBZ/HarpoonHoriz.cs
codetype=S1FObjectDefinitions.MBZ.HarpoonHoriz
[MBZ/LZEggman.txt]
name=LZ Eggman
sheet=Global/Eggman.gif
frame=-28, -32, 64, 56, 1, 1
[MBZ/LZHorizontalDoor.txt]
name=LZ Door Horizontal
sheet=MBZ/Objects.gif
frame=-64, -16, 128, 32, 93, 396
[MBZ/LZPushButton.txt]
name=LZ Push Button
sheet=MBZ/Objects.gif
frame=-16, -8, 32, 16, 223, 163
[MBZ/MBZSetup.txt]
name=MBZ Setup
hidden=true
[MBZ/MZEggman.txt]
name=MZ Eggman
sheet=Global/Eggman.gif
frame=-28, -32, 64, 56, 1, 1
[MBZ/OneWayDoor.txt]
; the mbz script is a copy of the sbz script, same sheet and all, so
name=One Way Door
xmlfile=SBZ/OneWayDoor.xml
[MBZ/PlasmaEmitter.txt]
name=Plasma Emitter
sheet=SBZ/Objects.gif
frame=-8, -8, 16, 16, 162, 397
[MBZ/SBZPlatform.txt]
name=SBZ Platform
sheet=MBZ/Objects.gif
frame=0, 0, 64, 14, 170, 295
[MBZ/SeeSaw.txt]
; the mbz script is a copy of the slz script, same sheet and all, so
name=SeeSaw
xmlfile=SLZ/SeeSaw.xml
[MBZ/SLZEggman.txt]
name=SLZ Eggman
sheet=Global/Eggman.gif
frame=-28, -32, 64, 56, 1, 1
[MBZ/SYZEggman.txt]
name=SYZ Eggman
sheet=Global/Eggman.gif
frame=-28, -32, 64, 56, 1, 1
[MBZ/TubeCover.txt]
; the SBZ ver has an outline, but i don't feel like that's necessary here?
name=Tube Cover
xmlfile=MBZ/TubeCover.xml
[MBZ/Water.txt]
name=Water
sheet=MBZ/Objects2.gif
frame=0, -8, 256, 16, 0, 129
[MBZ/WaterSplash.txt]
name=Water Splash
sheet=MBZ/Objects2.gif
frame=-10, -12, 20, 12, 202, 76
hidden=true
[MBZ/WreckingBall.txt]
sheet=GHZ/Objects2.gif
frame=-24, -24, 48, 48, 1, 77
