[MZ/BossFireball.txt]
name=Boss Fireball
sheet=MZ/Objects.gif
frame=-7, -23, 15, 31, 52, 114
hidden=true
[MZ/BreakBlock.txt]
name=Break Block
sheet=MZ/Objects.gif
frame=-16, -16, 32, 32, 317, 363
[MZ/ButtonPillar.txt]
name=Button Pillar
codefile=MZ/ButtonPillar.cs
codetype=S1ObjectDefinitions.MZ.ButtonPillar
[MZ/CFloor.txt]
name=C Floor
xmlfile=MZ/CFloor.xml
[MZ/ChainedCrusher.txt]
name=Chained Crusher
codefile=MZ/ChainedCrusher.cs
codetype=S1ObjectDefinitions.MZ.ChainedCrusher
[MZ/Eggman.txt]
name=Eggman
sheet=Global/Eggman.gif
frame=-28, -32, 64, 56, 1, 1
[MZ/FallingBlock.txt]
name=Falling Block
codefile=MZ/FallingBlock.cs
codetype=S1ObjectDefinitions.MZ.FallingBlock
[MZ/FallingLava.txt]
name=Falling Lava
xmlfile=MZ/FallingLava.xml
[MZ/Fireball.txt]
name=Fireball
codefile=MZ/Fireball.cs
codetype=S1FObjectDefinitions.MZ.Fireball
[MZ/GlassPillar.txt]
name=Glass Pillar
codefile=MZ/GlassPillar.cs
codetype=S1ObjectDefinitions.MZ.GlassPillar
[MZ/GrassFireball.txt]
name=Grass Fireball
sheet=MZ/Objects.gif
frame=-7, -23, 15, 31, 52, 114
hidden=true
[MZ/HCrusher.txt]
name=Horiz Crusher
codefile=MZ/HCrusher.cs
codetype=S1ObjectDefinitions.MZ.HCrusher
[MZ/HPlatform.txt]
name=H Platform
codefile=MZ/HPlatform.cs
codetype=S1ObjectDefinitions.MZ.HPlatform
[MZ/LargePlatform.txt]
name=Large Platform
xmlfile=MZ/LargePlatform.xml
[MZ/LavaFlow.txt]
name=Lava Flow
; on one hand a debug visualisation for this obj would be cool ig but it's not that pretty cuz it's just a really really big box (+ its end pos is hardcoded into the script)
xmlfile=MZ/LavaFlow.xml
[MZ/LavaGeyser.txt]
name=Lava Geyser
sheet=MZ/Objects.gif
frame=-24, -18, 48, 30, 268, 1
[MZ/LavaSplash.txt]
name=Lava Splash
sheet=MZ/Objects.gif
frame=-56, -18, 112, 30, 288, 332
hidden=true
[MZ/MZSetup.txt]
name=MZ Setup
hidden=true
[MZ/PushBlock.txt]
name=Push Block
xmlfile=MZ/PushBlock.xml
[MZ/PushButton.txt]
name=Push Button
sheet=MZ/Objects.gif
frame=-16, -8, 32, 16, 190, 230
[MZ/PushOutBlock.txt]
name=Push Out Block
codefile=MZ/PushOutBlock.cs
codetype=S1ObjectDefinitions.MZ.PushOutBlock
[MZ/RideBlock.txt]
name=Ride Block
xmlfile=MZ/RideBlock.xml
[MZ/ShortcutCheck.txt]
name=Shortcut Check
codefile=MZ/ShortcutCheck.cs
codetype=S1ObjectDefinitions.MZ.ShortcutCheck
[MZ/SwingPlat.txt]
name=Swing Platform
codefile=MZ/SwingPlat.cs
codetype=S1FObjectDefinitions.MZ.SwingPlat
[MZ/UFO.txt]
name=UFO
sheet=MZ/Objects.gif
frame=0, -11, 32, 21, 196, 355
hidden=true
