[SYZ/BossBarrier.txt]
name=Boss Barrier
xmlfile=SYZ/BossBarrier.xml
[SYZ/BossBlock.txt]
name=Boss Block
sheet=SYZ/Objects.gif
frame=-16, -16, 32, 32, 110, 152
[SYZ/Bumper.txt]
name=Bumper
sheet=SYZ/Objects.gif
frame=-14, -14, 28, 28, 1, 131
[SYZ/EdgeStabilizer.txt]
name=Edge Stabilizer
codefile=SYZ/EdgeStabilizer.cs
codetype=S1ObjectDefinitions.SYZ.EdgeStabilizer
[SYZ/Eggman.txt]
name=Eggman
sheet=Global/Eggman.gif
frame=-28, -32, 64, 56, 1, 1
[SYZ/HBlock.txt]
name=H Block
codefile=SYZ/HBlock.cs
codetype=S1ObjectDefinitions.SYZ.HBlock
[SYZ/HPlatform.txt]
name=H Platform
codefile=SYZ/HPlatform.cs
codetype=S1ObjectDefinitions.SYZ.HPlatform
[SYZ/HVSpikeBall.txt]
name=HV Spike Ball
codefile=SYZ/HVSpikeBall.cs
codetype=S1ObjectDefinitions.SYZ.HVSpikeBall
[SYZ/MovingBlock.txt]
name=Moving Block
codefile=SYZ/MovingBlock.cs
codetype=S1ObjectDefinitions.SYZ.MovingBlock
[SYZ/Push Block.txt]
; even if prop val is technically used like the other Push Blocks, the sprites for the large ver don't really work, so let's pretend that prop val's unused and give this object a basic def
name=Push Block
sheet=SYZ/Objects.gif
frame=-16, -16, 32, 32, 119, 34
[SYZ/PushButton.txt]
name=Push Button
sheet=SYZ/Objects.gif
frame=-16, -8, 32, 16, 1, 161
[SYZ/RLight.txt]
name=Rotating Light
sheet=SYZ/Objects.gif
frame=-16, -8, 32, 16, 143, 152
[SYZ/RotatingSpike.txt]
name=Rotating Spike
codefile=SYZ/RotatingSpike.cs
codetype=S1ObjectDefinitions.SYZ.RotatingSpike
[SYZ/RSpikeChain.txt]
name=R Spike Chain
codefile=SYZ/RSpikeChain.cs
codetype=S1ObjectDefinitions.SYZ.RSpikeChain
[SYZ/ShortcutCheck.txt]
; bounds are the same as the MZ one, but let's keep it separate in case they change the bounds later or something
name=Shortcut Check
codefile=SYZ/ShortcutCheck.cs
codetype=S1FObjectDefinitions.SYZ.ShortcutCheck
[SYZ/SolidBlock.txt]
name=Solid Block
sheet=SYZ/Objects.gif
frame=-16, -16, 32, 32, 119, 34
[SYZ/StaticPlatform.txt]
name=Static Platform
codefile=SYZ/StaticPlatform.cs
codetype=S1ObjectDefinitions.SYZ.StaticPlatform
[SYZ/SYZSetup.txt]
name=SYZ Setup
hidden=true
[SYZ/VBlock.txt]
name=V Block
codefile=SYZ/VBlock.cs
codetype=S1ObjectDefinitions.SYZ.VBlock
[SYZ/VerticalDoor.txt]
name=Vertical Door
codefile=SYZ/VerticalDoor.cs
codetype=S1ObjectDefinitions.SYZ.VerticalDoor
[SYZ/VPlatform.txt]
name=V Platform
codefile=SYZ/VPlatform.cs
codetype=S1ObjectDefinitions.SYZ.VPlatform
