[2PVS/2PVSSetup.txt]
name=2P VS Setup
sheet=LevelSelect/Icons.gif
frame=-14, -6, 28, 12, 93, 110
[2PVS/2PVSMenu1.txt]
name=2P VS Menu 1
xmlfile=2PVS/2PVSMenu1.xml
[2PVS/2PVSMenu2.txt]
name=2P VS Menu 2
xmlfile=2PVS/2PVSMenu2.xml
[2PVS/2PVSMenu3.txt]
name=2P VS Menu 3
xmlfile=2PVS/2PVSMenu3.xml
[2PVS/2PVSMenu4.txt]
; origins object, copy of menu 2
name=2P VS Menu 4
xmlfile=2PVS/2PVSMenu2.xml
[2PVS/ActResults.txt]
name=Act Results
sheet=LevelSelect/Icons.gif
frame=-48, 0, 96, 14, 1, 136
hidden=true
[2PVS/GameResults.txt]
; this object *is* placed in a scene in origins, but that's a mistake from bumping around object IDs
name=Game Results
sheet=LevelSelect/Icons.gif
frame=-48, 0, 96, 14, 1, 136
hidden=true
[2PVS/SSResults.txt]
name=SS Results
sheet=LevelSelect/Icons.gif
frame=-48, 0, 96, 14, 1, 136
hidden=true
[2PVS/SSResultSingle.txt]
name=SS Single Result
sheet=LevelSelect/Icons.gif
frame=-48, 0, 96, 14, 1, 136
hidden=true
[2PVS/VSGame.txt]
name=VS Game
xmlfile=2PVS/VSGame.xml
[2PVS/ZoneButton.txt]
name=Zone Button
sheet=LevelSelect/Icons.gif
frame=4, -13, 32, 24, 1, 85
hidden=true
[2PVS/ZoneResults.txt]
name=Zone Results
sheet=LevelSelect/Icons.gif
frame=-48, 0, 96, 14, 1, 136
hidden=true
