[ARZ/AirBubble.txt]
name=Air Bubble
; wrong sheet is intentional, object actually uses CPZ sheets in-game
sheet=CPZ/Objects3.gif
frame=-2, -2, 4, 4, 157, 2
hidden=true
[ARZ/AirBubbler.txt]
name=Air Bubbler
; obj is identical to CPZ (including using a CPZ sheet)
xmlfile=CPZ/AirBubbler.xml
[ARZ/Arrow.txt]
name=Arrow
sheet=ARZ/Objects.gif
frame=-16, -4, 32, 7, 1, 69
hidden=true
[ARZ/ArrowLauncher.txt]
name=Arrow Launcher
codefile=ARZ/ArrowLauncher.cs
codetype=S2ObjectDefinitions.ARZ.ArrowLauncher
[ARZ/ARZSetup.txt]
name=ARZ Setup
hidden=true
[ARZ/BreakablePillar.txt]
name=Breakable Pillar
codefile=ARZ/BreakablePillar.cs
codetype=S2ObjectDefinitions.ARZ.BreakablePillar
[ARZ/BreakoffPillar.txt]
name=Breakoff Pillar
codefile=ARZ/BreakoffPillar.cs
codetype=S2ObjectDefinitions.ARZ.BreakoffPillar
[ARZ/Brick.txt]
name=Brick
codefile=ARZ/Generic.cs
codetype=S2ObjectDefinitions.ARZ.Brick
[ARZ/CollapsingFloor.txt]
name=C Floor
codefile=ARZ/CollapsingFloor.cs
codetype=S2ObjectDefinitions.ARZ.CollapsingFloor
[ARZ/CountdownBubble.txt]
name=Countdown Bubble
; wrong sheet is intentional, object actually uses CPZ sheets in-game
sheet=CPZ/Objects3.gif
frame=-8, -10, 16, 20, 52, 1
hidden=true
[ARZ/Eggman.txt]
; called "ARZ Eggman" in MBZ, but we'll stick with the normal name here
name=Eggman
codefile=ARZ/Generic.cs
codetype=S2ObjectDefinitions.ARZ.Eggman
[ARZ/EggmanArrow.txt]
name=Eggman Arrow
codefile=ARZ/Generic.cs
codetype=S2ObjectDefinitions.ARZ.EggmanArrow
[ARZ/EggmanHammer.txt]
name=Eggman Hammer
codefile=ARZ/Generic.cs
codetype=S2ObjectDefinitions.ARZ.EggmanHammer
[ARZ/EggmanTotemPole.txt]
name=Eggman Totem
codefile=ARZ/Generic.cs
codetype=S2ObjectDefinitions.ARZ.EggmanTotem
[ARZ/FallingPillar.txt]
name=Falling Pillar
codefile=ARZ/FallingPillar.cs
codetype=S2ObjectDefinitions.ARZ.FallingPillar
[ARZ/FPlatform.txt]
name=Fall Platform
codefile=ARZ/FPlatform.cs
codetype=S2ObjectDefinitions.ARZ.FPlatform
[ARZ/HPlatform.txt]
name=H Platform
codefile=ARZ/Platform.cs
codetype=S2ObjectDefinitions.ARZ.HPlatform
[ARZ/Leaf.txt]
name=Leaf
sheet=ARZ/Objects.gif
frame=-4, -3, 8, 7, 155, 207
hidden=true
[ARZ/LeafSpawner.txt]
name=Leaf Spawner
codefile=ARZ/LeafSpawner.cs
codetype=S2ObjectDefinitions.ARZ.LeafSpawner
[ARZ/OneWayDoor.txt]
name=One Way Door
codefile=ARZ/OneWayDoor.cs
codetype=S2ObjectDefinitions.ARZ.OneWayDoor
[ARZ/PSwitch_V2.txt]
name=Plane Sw V2
; thanks sonic origins (it's the same as the normal version except always active, but that doesn't matter here)
codefile=Global/PSwitch_V.cs
codetype=S2ObjectDefinitions.Global.PSwitch_V
[ARZ/Raft.txt]
name=Raft
sheet=ARZ/Objects.gif
frame=-32, -8, 64, 16, 126, 191
[ARZ/RotatePlatform.txt]
name=Rotate Platform
codefile=ARZ/RotatePlatform.cs
codetype=S2ObjectDefinitions.ARZ.RotatePlatform
[ARZ/SwingPlat.txt]
name=Swing Platform
codefile=ARZ/SwingPlat.cs
codetype=S2ObjectDefinitions.ARZ.SwingPlat
[ARZ/VPlatform.txt]
name=V Platform
codefile=ARZ/Platform.cs
codetype=S2ObjectDefinitions.ARZ.VPlatform
[ARZ/VPlatform2.txt]
name=V Platform 2
codefile=ARZ/Platform.cs
codetype=S2ObjectDefinitions.ARZ.VPlatform2
[ARZ/Water.txt]
name=Water
sheet=ARZ/Objects2.gif
frame=0, -7, 256, 16, 0, 0
[ARZ/WaterSplash.txt]
name=Water Splash
sheet=ARZ/Objects3.gif
frame=-10, -32, 20, 32, 1, 95
hidden=true
