[CNZ/BossWall.txt]
name=Boss Wall
codefile=CNZ/BossWall.cs
codetype=S2ObjectDefinitions.CNZ.BossWall
[CNZ/Bumper.txt]
; called "OBJECT NAME" in the Origins Bounce House mission
; not going with that one for obvious reasons lol
name=Bumper
codefile=CNZ/Generic.cs
codetype=S2ObjectDefinitions.CNZ.Bumper
[CNZ/CNZSetup.txt]
name=CNZ Setup
hidden=true
[CNZ/ConveyorBelt.txt]
name=Conveyor Belt
codefile=CNZ/ConveyorBelt.cs
codetype=S2ObjectDefinitions.CNZ.ConveyorBelt
[CNZ/DPlunger.txt]
name=D Plunger
xmlfile=CNZ/DPlunger.xml
[CNZ/Eggman.txt]
; called "CNZ Eggman" in MBZ, but we'll stick with the normal name here
name=Eggman
codefile=CNZ/Generic.cs
codetype=S2ObjectDefinitions.CNZ.Eggman
[CNZ/EggmanBomb.txt]
name=Eggman Bomb
codefile=CNZ/Generic.cs
codetype=S2ObjectDefinitions.CNZ.EggmanBomb
[CNZ/EggmanClaw.txt]
name=Eggman Claw
codefile=CNZ/Generic.cs
codetype=S2ObjectDefinitions.CNZ.EggmanClaw
[CNZ/Elevator.txt]
name=Elevator
codefile=CNZ/Elevator.cs
codetype=S2ObjectDefinitions.CNZ.Elevator
[CNZ/HBlock.txt]
name=H Block
codefile=CNZ/MovingBlock.cs
codetype=S2ObjectDefinitions.CNZ.HBlock
[CNZ/HexBumper.txt]
name=Hex Bumper
codefile=CNZ/HexBumper.cs
codetype=S2ObjectDefinitions.CNZ.HexBumper
[CNZ/HFlipper.txt]
name=H Flipper
codefile=CNZ/HFlipper.cs
codetype=S2ObjectDefinitions.CNZ.HFlipper
[CNZ/SlotDisplay.txt]
name=Slot Display
xmlfile=CNZ/SlotDisplay.xml
[CNZ/SlotMachine.txt]
name=Slot Machine
xmlfile=CNZ/SlotMachine.xml
[CNZ/SlotPrize.txt]
name=Slot Prize
sheet=CNZ/Objects.gif
frame=-8, -8, 16, 16, 110, 256
hidden=true
[CNZ/SnakePlatform.txt]
name=Snake Platform
sheet=CNZ/Objects.gif
frame=-40, -32, 80, 64, 1, 34
[CNZ/Spinner_H.txt]
name=Spinner H
codefile=CNZ/Spinner_H.cs
codetype=S2ObjectDefinitions.CNZ.Spinner_H
[CNZ/Spinner_V.txt]
name=Spinner V
codefile=CNZ/Spinner_V.cs
codetype=S2ObjectDefinitions.CNZ.Spinner_V
[CNZ/TargetBumper.txt]
name=Target Bumper
codefile=CNZ/TargetBumper.cs
codetype=S2ObjectDefinitions.CNZ.TargetBumper
[CNZ/TriBumper.txt]
name=Tri Bumper
codefile=CNZ/TriBumper.cs
codetype=S2ObjectDefinitions.CNZ.TriBumper
[CNZ/TubeSwitch.txt]
name=Tube Switch
xmlfile=CNZ/TubeSwitch.xml
[CNZ/VBlock.txt]
name=V Block
codefile=CNZ/MovingBlock.cs
codetype=S2ObjectDefinitions.CNZ.VBlock
[CNZ/VFlipper.txt]
name=V Flipper
codefile=CNZ/Generic.cs
codetype=S2ObjectDefinitions.CNZ.VFlipper
[CNZ/VPlunger.txt]
name=V Plunger
codefile=CNZ/Generic.cs
codetype=S2ObjectDefinitions.CNZ.VPlunger
