[CPZ/Accessory.txt]
name=Accessory
xmlfile=CPZ/Accessory.xml
[CPZ/AirBubble.txt]
name=Air Bubble
sheet=CPZ/Objects3.gif
frame=-16, -16, 32, 32, 222, 1
hidden=true
[CPZ/AirBubbler.txt]
name=Air Bubbler
xmlfile=CPZ/AirBubbler.xml
[CPZ/BreakBlock.txt]
name=Break Block
sheet=CPZ/Objects.gif
frame=-16, -16, 32, 32, 165, 223
[CPZ/BumpingPlatform.txt]
name=Bumping Platform
codefile=CPZ/BumpingPlatform.cs
codetype=S2ObjectDefinitions.CPZ.BumpingPlatform
[CPZ/ChemicalBall.txt]
name=Chemical Ball
codefile=CPZ/ChemicalBall.cs
codetype=S2ObjectDefinitions.CPZ.ChemicalBall
[CPZ/ChemicalDrop.txt]
name=Chemical Drop
codefile=CPZ/Eggman.cs
codetype=S2ObjectDefinitions.CPZ.ChemicalDrop
[CPZ/ChemicalSplash.txt]
name=Chemical Splash
codefile=CPZ/Eggman.cs
codetype=S2ObjectDefinitions.CPZ.ChemicalSplash
[CPZ/CountdownBubble.txt]
name=Countdown Bubble
sheet=CPZ/Objects3.gif
frame=-8, -10, 16, 20, 52, 1
hidden=true
[CPZ/CPZSetup.txt]
name=CPZ Setup
hidden=true
[CPZ/Eggman.txt]
; called "CPZ Eggman" in MBZ, but we'll stick with the normal name here
name=Eggman
codefile=CPZ/Eggman.cs
codetype=S2ObjectDefinitions.CPZ.Eggman
[CPZ/EggmanChemicalDropper.txt]
name=Chemical Dropper
codefile=CPZ/Eggman.cs
codetype=S2ObjectDefinitions.CPZ.ChemicalDropper
[CPZ/Fireball.txt]
; not sure if this is supposed to be hidden or not? i guess it's not supposed to be?
name=Fireball
sheet=CPZ/Objects.gif
frame=-6, -23, 12, 28, 5, 161
[CPZ/HPlatform.txt]
name=H Platform
codefile=CPZ/Platform.cs
codetype=S2ObjectDefinitions.CPZ.HPlatform
[CPZ/OneWayDoor.txt]
name=One Way Door
codefile=CPZ/OneWayDoor.cs
codetype=S2ObjectDefinitions.CPZ.OneWayDoor
[CPZ/RotatePlatform.txt]
name=Rotate Platform
codefile=CPZ/RotatePlatform.cs
codetype=S2ObjectDefinitions.CPZ.RotatePlatform
[CPZ/RotatingStair.txt]
name=Rotating Stair
codefile=CPZ/RotatingStair.cs
codetype=S2ObjectDefinitions.CPZ.RotatingStair
[CPZ/SpeedBooster.txt]
name=Speed Booster
codefile=CPZ/SpeedBooster.cs
codetype=S2ObjectDefinitions.CPZ.SpeedBooster
[CPZ/Staircase.txt]
name=Staircase
codefile=CPZ/Staircase.cs
codetype=S2ObjectDefinitions.CPZ.Staircase
[CPZ/TippingFloor.txt]
name=Tipping Floor
codefile=CPZ/TippingFloor.cs
codetype=S2ObjectDefinitions.CPZ.TippingFloor
[CPZ/TransportTube.txt]
name=Transport Tube
codefile=CPZ/TransportTube.cs
codetype=S2ObjectDefinitions.CPZ.TransportTube
[CPZ/TubeSpring.txt]
name=Tube Spring
codefile=CPZ/TubeSpring.cs
codetype=S2ObjectDefinitions.CPZ.TubeSpring
[CPZ/VPlatform.txt]
name=V Platform
codefile=CPZ/Platform.cs
codetype=S2ObjectDefinitions.CPZ.VPlatform
[CPZ/VPlatform2.txt]
name=V Platform 2
codefile=CPZ/Platform.cs
codetype=S2ObjectDefinitions.CPZ.VPlatform2
[CPZ/Water.txt]
name=Water
sheet=CPZ/Objects2.gif
frame=0, -8, 256, 16, 0, 0
[CPZ/WaterSplash.txt]
name=Water Splash
sheet=CPZ/Objects3.gif
frame=-16, -31, 31, 31, 116, 96
hidden=true
