[Enemies/Antenna.txt]
name=Antenna
sheet=SCZ/Objects.gif
frame=-4, -16, 8, 30, 195, 159
[Enemies/Aquis.txt]
name=Aquis
codefile=Enemies/Aquis.cs
codetype=S2ObjectDefinitions.Enemies.Aquis
[Enemies/AquisShot.txt]
name=Aquis Shot
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.AquisShot
[Enemies/Asteron.txt]
name=Asteron
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Asteron
[Enemies/AsteronSpike.txt]
; called AsteronSpike (no space) in Origins's SCZ missions, we'll keep the space here
name=Asteron Spike
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.AsteronSpike
[Enemies/Balkiry.txt]
name=Balkiry
codefile=Enemies/Balkiry.cs
codetype=S2ObjectDefinitions.Enemies.Balkiry
[Enemies/Ball.txt]
name=Ball
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Ball
[Enemies/Batbot.txt]
name=Batbot
xmlfile=Enemies/Batbot.xml
[Enemies/Bee.txt]
name=Bee
codefile=Enemies/Bee.cs
codetype=S2ObjectDefinitions.Enemies.Bee
[Enemies/BeeShot.txt]
name=Bee Shot
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.BeeShot
[Enemies/BigTurtloid.txt]
name=Big Turtloid
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.BigTurtloid
[Enemies/Bubbler.txt]
name=Bubbler
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Bubbler
[Enemies/BubblersMother.txt]
name=Bubblers Mother
codefile=Enemies/BubblersMother.cs
codetype=S2ObjectDefinitions.Enemies.BubblersMother
[Enemies/Buzzer.txt]
name=Buzzer
codefile=Enemies/Buzzer.cs
codetype=S2ObjectDefinitions.Enemies.Buzzer
[Enemies/BuzzerShot.txt]
name=Buzzer Shot
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.BuzzerShot
[Enemies/ChopChop.txt]
name=Chop Chop
codefile=Enemies/ChopChop.cs
codetype=S2ObjectDefinitions.Enemies.ChopChop
[Enemies/Clucker.txt]
name=Clucker
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Clucker
[Enemies/CluckerBase.txt]
name=Clucker Base
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.CluckerBase
[Enemies/CluckerShot.txt]
name=Clucker Shot
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.CluckerShot
[Enemies/Coconut.txt]
name=Coconut
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Coconut
[Enemies/Coconuts.txt]
name=Coconuts
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Coconuts
[Enemies/Crawl.txt]
name=Crawl
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Crawl
[Enemies/Crawlton.txt]
name=Crawlton
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Crawlton
[Enemies/Flasher.txt]
name=Flasher
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Flasher
[Enemies/Grabber.txt]
name=Grabber
codefile=Enemies/Grabber.cs
codetype=S2ObjectDefinitions.Enemies.Grabber
[Enemies/GrabberShot.txt]
name=Grabber Shot
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.GrabberShot
[Enemies/Grounder.txt]
name=Grounder
codefile=Enemies/Grounder.cs
codetype=S2ObjectDefinitions.Enemies.Grounder
[Enemies/Grounder2.txt]
name=Grounder2
codefile=Enemies/Grounder.cs
codetype=S2ObjectDefinitions.Enemies.Grounder2
[Enemies/Jellygnite.txt]
name=Jellygnite
xmlfile=Enemies/Jellygnite.xml
[Enemies/Masher.txt]
name=Masher
codefile=Enemies/Masher.cs
codetype=S2ObjectDefinitions.Enemies.Masher
[Enemies/Nebula.txt]
name=Nebula
codefile=Enemies/Nebula.cs
codetype=S2ObjectDefinitions.Enemies.Nebula
[Enemies/NebulaBomb.txt]
name=Nebula Bomb
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.NebulaBomb
[Enemies/Octus.txt]
name=Octus
codefile=Enemies/Octus.cs
codetype=S2ObjectDefinitions.Enemies.Octus
[Enemies/OctusShot.txt]
; called OctusShot (no space) in Origins's SCZ missions, we'll stick with the OOZ name here
name=Octus Shot
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.OctusShot
[Enemies/Redz.txt]
name=Redz
xmlfile=Enemies/Redz.xml
[Enemies/RedzFire.txt]
name=Redz Fire
sheet=HPZ/Objects.gif
frame=-7, -8, 14, 16, 151, 112
hidden=true
[Enemies/Rexon.txt]
name=Rexon
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Rexon
[Enemies/RexonShot.txt]
name=Rexon Shot
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.RexonShot
[Enemies/Shellcracker.txt]
name=Shellcracker
codefile=Enemies/Shellcracker.cs
codetype=S2ObjectDefinitions.Enemies.Shellcracker
[Enemies/Slicer.txt]
name=Slicer
codefile=Enemies/Slicer.cs
codetype=S2ObjectDefinitions.Enemies.Slicer
[Enemies/SlicerArm.txt]
name=Slicer Arm
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.SlicerArm
[Enemies/SmallTurtloid.txt]
name=SmallTurtloid
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.SmallTurtloid
[Enemies/Snail.txt]
name=Snail
codefile=Enemies/Snail.cs
codetype=S2ObjectDefinitions.Enemies.Snail
[Enemies/Sol.txt]
name=Sol
codefile=Enemies/Sol.cs
codetype=S2ObjectDefinitions.Enemies.Sol
[Enemies/Spiker.txt]
name=Spiker
codefile=Enemies/Spiker.cs
codetype=S2ObjectDefinitions.Enemies.Spiker
[Enemies/SpinyFloor.txt]
name=Spiny Floor
codefile=Enemies/SpinyFloor.cs
codetype=S2ObjectDefinitions.Enemies.SpinyFloor
[Enemies/SpinyShot.txt]
name=Spiny Shot
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.SpinyShot
[Enemies/SpinyWall.txt]
name=Spiny Wall
codefile=Enemies/SpinyWall.cs
codetype=S2ObjectDefinitions.Enemies.SpinyWall
[Enemies/Stegway.txt]
name=Stegway
xmlfile=Enemies/Stegway.xml
[Enemies/TurtloidShot.txt]
name=Turtloid Shot
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.TurtloidShot
[Enemies/Whisp.txt]
name=Whisp
codefile=Enemies/Generic.cs
codetype=S2ObjectDefinitions.Enemies.Whisp
