[Global/ActFinish.txt]
name=Act Finish
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
hidden=true
[Global/AnimalPrison.txt]
name=Animal Prison
xmlfile=Global/AnimalPrison.xml
[Global/BlueShield.txt]
name=Blue Shield
sheet=Global/Items.gif
frame=-16, -16, 32, 32, 190, 50
hidden=true
[Global/BrokenMonitor.txt]
name=Broken Monitor
sheet=Global/Items.gif
frame=-16, 0, 32, 16, 18, 34
hidden=true
[Global/BubbleShield.txt]
name=Bubble Shield
sheet=Global/Items3.gif
frame=-24, -24, 48, 48, 1, 1
hidden=true
[Global/DeathEvent.txt]
name=Death Event
sheet=Global/Display.gif
frame=-16, -16, 32, 32, 1, 143
hidden=true
[Global/DebugMode.txt]
; in s1 we used the unused CD life icon, which is how it was in-game too, but since s2's in-game frame points to a blank space (or the letter A in Origins lol) let's just use the continue icon
name=Debug Mode
sheet=Global/Display.gif
frame=-8, -11, 16, 23, 178, 113
hidden=true
[Global/DustPuff.txt]
name=Dust Puff
sheet=Global/Items.gif
frame=-7, -11, 13, 14, 85, 143
hidden=true
[Global/Explosion.txt]
name=Explosion
sheet=Global/Items2.gif
frame=-8, -8, 16, 16, 230, 18
hidden=true
[Global/FireShield.txt]
name=Fire Shield
sheet=Global/Items3.gif
frame=-24, -21, 48, 34, 50, 140
hidden=true
[Global/HUD.txt]
name=HUD
sheet=Global/Display.gif
frame=0, 0, 40, 43, 1, 1
debug=true
[Global/InstaShield.txt]
name=Insta Shield
sheet=Global/Items3.gif
frame=-16, -24, 40, 40, 173, 214
hidden=true
[Global/Invincibility.txt]
name=Invincibility
sheet=Global/Items.gif
frame=-15, -15, 31, 31, 200, 1
hidden=true
[Global/InvisibleBlock.txt]
name=Invisible Block
codefile=Global/InvisibleBlock.cs
codetype=S2ObjectDefinitions.Global.InvisibleBlock
[Global/LightningShield.txt]
name=LightningShield
sheet=Global/Items3.gif
frame=-24, -24, 48, 48, 50, 91
hidden=true
[Global/LightningSpark.txt]
name=Lightning Spark
sheet=Global/Items3.gif
frame=-8, -8, 16, 16, 157, 84
hidden=true
[Global/LoseRing.txt]
name=Lose Ring
sheet=Global/Items.gif
frame=-8, -8, 16, 16, 1, 1
hidden=true
[Global/Monitor.txt]
name=Monitor
xmlfile=Global/Monitor.xml
[Global/MusicEvent.txt]
name=Music Event
hidden=true
[Global/ObjectScore.txt]
name=Object Score
sheet=Global/Display.gif
frame=-8, 0, 16, 10, 66, 53
hidden=true
[Global/PSwitch_H.txt]
name=Plane Sw H
codefile=Global/PSwitch_H.cs
codetype=S2ObjectDefinitions.Global.PSwitch_H
[Global/PSwitch_V.txt]
name=Plane Sw V
codefile=Global/PSwitch_V.cs
codetype=S2ObjectDefinitions.Global.PSwitch_V
[Global/RedSpring.txt]
name=Red Spring
xmlfile=Global/RedSpring.xml
[Global/Ring.txt]
name=Ring
xmlfile=Global/Ring.xml
[Global/RingSparkle.txt]
name=Ring Sparkle
sheet=Global/Items.gif
frame=-8, -8, 16, 16, 1, 219
hidden=true
[Global/SignPost.txt]
name=Sign Post
xmlfile=Global/SignPost.xml
[Global/SmokePuff.txt]
name=Smoke Puff
sheet=Global/Items2.gif
frame=-8, -8, 16, 16, 230, 18
hidden=true
[Global/Spikes.txt]
name=Spikes
codefile=Global/Spikes.cs
codetype=S2ObjectDefinitions.Global.Spikes
[Global/Springboard.txt]
name=Springboard
codefile=Global/Springboard.cs
codetype=S2ObjectDefinitions.Global.Springboard
[Global/StageSetup.txt]
name=Stage Setup
hidden=true
[Global/StarPost.txt]
name=Star Post
xmlfile=Global/StarPost.xml
[Global/SuperSpark.txt]
name=Super Spark
sheet=Global/Items.gif
frame=-8, -8, 16, 16, 200, 33
hidden=true
[Global/TitleCard.txt]
name=Title Card
xmlfile=Global/TitleCard.xml
[Global/YellowSpring.txt]
name=Yellow Spring
codefile=Global/YellowSpring.cs
codetype=S2ObjectDefinitions.Global.YellowSpring
[Global/YBoundAdjust.txt]
name=Y Bound Adjust
codefile=Global/YBoundAdjust.cs
codetype=S2ObjectDefinitions.Global.YBoundAdjust
