[MPZ/BeltActivation.txt]
name=Belt Activation
codefile=MPZ/BeltActivation.cs
codetype=S2ObjectDefinitions.MPZ.BeltActivation
[MPZ/BeltPlatform.txt]
name=Belt Platform
codefile=MPZ/BeltPlatform.cs
codetype=S2ObjectDefinitions.MPZ.BeltPlatform
[MPZ/BoltEnd.txt]
name=Bolt End
codefile=MPZ/DecoSprite.cs
codetype=S2ObjectDefinitions.MPZ.BoltEnd
[MPZ/ButtonBridge.txt]
name=Button Bridge
codefile=MPZ/ButtonBridge.cs
codetype=S2ObjectDefinitions.MPZ.ButtonBridge
[MPZ/ConveyorBelt.txt]
name=Conveyor Belt
codefile=MPZ/ConveyorBelt.cs
codetype=S2ObjectDefinitions.MPZ.ConveyorBelt
[MPZ/CogPlatform.txt]
name=Cog Platform
xmlfile=MPZ/CogPlatform.xml
[MPZ/Cylinder.txt]
name=Cylinder
codefile=MPZ/Cylinder.cs
codetype=S2ObjectDefinitions.MPZ.Cylinder
[MPZ/Eggman.txt]
; called "MPZ Eggman" in MBZ, but we'll stick with the normal name here
name=Eggman
codefile=MPZ/Eggman.cs
codetype=S2ObjectDefinitions.MPZ.Eggman
[MPZ/EggmanBalloon.txt]
name=Eggman Balloon
codefile=MPZ/Eggman.cs
codetype=S2ObjectDefinitions.MPZ.EggmanBalloon
[MPZ/EggmanLaser.txt]
; called "Eggman Laser 2" in MBZ since OOZ took "Eggman Laser"
; we'll keep the base MPZ name in here
name=Eggman Laser
codefile=MPZ/Eggman.cs
codetype=S2ObjectDefinitions.MPZ.EggmanLaser
[MPZ/EPlatform.txt]
name=E Platform
codefile=MPZ/Platform.cs
codetype=S2ObjectDefinitions.MPZ.EPlatform
[MPZ/FPlatform.txt]
name=Fall Platform
codefile=MPZ/Platform.cs
codetype=S2ObjectDefinitions.MPZ.FPlatform
[MPZ/Guage.txt]
name=Guage
codefile=MPZ/DecoSprite.cs
codetype=S2ObjectDefinitions.MPZ.Guage
[MPZ/HorizontalDoor.txt]
name=Horizontal Door
codefile=MPZ/HorizontalDoor.cs
codetype=S2ObjectDefinitions.MPZ.HorizontalDoor
[MPZ/HPlatform.txt]
name=H Platform
codefile=MPZ/Platform.cs
codetype=S2ObjectDefinitions.MPZ.HPlatform
[MPZ/HPlatform2.txt]
name=H Platform 2
codefile=MPZ/Platform.cs
codetype=S2ObjectDefinitions.MPZ.HPlatform2
[MPZ/LargeGear.txt]
name=Large Gear
xmlfile=MPZ/LargeGear.xml
[MPZ/LargePiston.txt]
name=Large Piston
codefile=MPZ/LargePiston.cs
codetype=S2ObjectDefinitions.MPZ.LargePiston
[MPZ/LavaBubble.txt]
name=Lava Bubble
sheet=MPZ/Objects.gif
frame=-7, 2, 14, 8, 1, 1
[MPZ/LPlatform.txt]
name=L Platform
sheet=MPZ/Objects.gif
frame=-32, -12, 64, 24, 383, 207
[MPZ/MPlatform.txt]
name=M Platform
; this platform's movement is kind of erratic so it turns out it doesn't really lend itself well to a debug render..
;codefile=MPZ/Platform.cs
;codetype=S2ObjectDefinitions.MPZ.MPlatform
sheet=MPZ/Objects.gif
frame=-32, -12, 64, 24, 383, 207
[MPZ/MPZSetup.txt]
name=MPZ Setup
hidden=true
[MPZ/Nut.txt]
name=Nut
codefile=MPZ/Nut.cs
codetype=S2ObjectDefinitions.MPZ.Nut
[MPZ/OneWayDoor.txt]
name=One Way Door
codefile=MPZ/OneWayDoor.cs
codetype=S2ObjectDefinitions.MPZ.OneWayDoor
[MPZ/PlatConveyor.txt]
name=Plat Conveyor
codefile=MPZ/DecoSprite.cs
codetype=S2ObjectDefinitions.MPZ.PlatConveyor
[MPZ/PushButton.txt]
name=Push Button
sheet=MPZ/Objects.gif
frame=-16, -8, 32, 16, 317, 190
[MPZ/SmallCog.txt]
name=Small Cog
codefile=MPZ/DecoSprite.cs
codetype=S2ObjectDefinitions.MPZ.SmallCog
[MPZ/SmallPiston.txt]
name=Small Piston
codefile=MPZ/SmallPiston.cs
codetype=S2ObjectDefinitions.MPZ.SmallPiston
[MPZ/Spear.txt]
name=Spear
xmlfile=MPZ/Spear.xml
[MPZ/SpearBlock.txt]
name=Spear Block
codefile=MPZ/SpearBlock.cs
codetype=S2ObjectDefinitions.MPZ.SpearBlock
[MPZ/SteamPiston.txt]
name=Steam Piston
sheet=MPZ/Objects.gif
frame=-16, -16, 32, 32, 166, 93
[MPZ/Transporter.txt]
name=Transporter
codefile=MPZ/Transporter.cs
codetype=S2ObjectDefinitions.MPZ.Transporter
[MPZ/TransSprite.txt]
name=Trans Sprite
codefile=MPZ/DecoSprite.cs
codetype=S2ObjectDefinitions.MPZ.TransSprite
[MPZ/VPlatform.txt]
name=V Platform
codefile=MPZ/Platform.cs
codetype=S2ObjectDefinitions.MPZ.VPlatform
[MPZ/VPlatform2.txt]
name=V Platform 2
codefile=MPZ/Platform.cs
codetype=S2ObjectDefinitions.MPZ.VPlatform2
[MPZ/WallBumper.txt]
name=Wall Bumper
codefile=MPZ/WallBumper.cs
codetype=S2ObjectDefinitions.MPZ.WallBumper
[MPZ/WheelPlatform.txt]
name=Wheel Platform
codefile=MPZ/WheelPlatform.cs
codetype=S2ObjectDefinitions.MPZ.WheelPlatform
