[Title/Sega.txt]
name=Sega
sheet=Title/Title.gif
frame=-31, -36, 62, 72, 1, 226
[Title/STScreen.txt]
; object is made out of tiles, so no render of that possible...
; (sure, we *could* draw tiles in the object sprite with a C# def, but.. that's a bit overkill-)
name=ST Screen
hidden=true
[Title/STLogo.txt]
name=ST Logo
xmlfile=Title/STLogo.xml
[Title/KLogo.txt]
name=K Logo
xmlfile=Title/STLogo.xml
[Title/TinkleStars.txt]
name=Twinkle Stars
sheet=Title/Title.gif
frame=-12, -12, 23, 23, 441, 43
hidden=true
[Title/ShootingStar.txt]
name=Shooting Star
sheet=Title/Title.gif
frame=-4, -4, 7, 7, 417, 59
hidden=true
[Title/Start.txt]
name=Start Message
sheet=Title/Title.gif
frame=-49, -1, 98, 9, 1, 380
hidden=true
