[WFZ/BeltPlatform.txt]
name=Belt Platform
codefile=WFZ/BeltPlatform.cs
codetype=S2ObjectDefinitions.WFZ.BeltPlatform
[WFZ/BeltPlatformS.txt]
name=Belt Platform S
codefile=WFZ/BeltPlatformS.cs
codetype=S2ObjectDefinitions.WFZ.BeltPlatformS
[WFZ/Cloud.txt]
name=Cloud
xmlfile=WFZ/Cloud.xml
[WFZ/CockpitBackground.txt]
name=Cockpit Background
sheet=SCZ/Objects.gif
frame=-4, -16, 8, 32, 194, 99
[WFZ/ConveyorBelt.txt]
name=Conveyor Belt
codefile=WFZ/ConveyorBelt.cs
codetype=S2ObjectDefinitions.WFZ.ConveyorBelt
[WFZ/ConveyorWheel.txt]
name=Conveyor Wheel
sheet=SCZ/Objects.gif
frame=-16, -16, 32, 32, 203, 119
[WFZ/Eggman.txt]
; called "WFZ Eggman" in MBZ, but we'll stick with the normal name here
name=Eggman
codefile=WFZ/Eggman.cs
codetype=S2ObjectDefinitions.WFZ.Eggman
[WFZ/EggmanBarrier.txt]
name=Eggman Barrier
codefile=WFZ/Generic.cs
codetype=S2ObjectDefinitions.WFZ.EggmanBarrier
[WFZ/EggmanDispenser.txt]
name=Eggman Dispenser
codefile=WFZ/Generic.cs
codetype=S2ObjectDefinitions.WFZ.EggmanDispenser
[WFZ/EggmanLaser.txt]
; called "Eggman Laser 3" in MBZ since OOZ took "Eggman Laser" and MPZ took "Eggman Laser 2"
; we'll keep the base WFZ name in here
name=Eggman Laser
codefile=WFZ/Generic.cs
codetype=S2ObjectDefinitions.WFZ.EggmanLaser
[WFZ/EggmanPlatform.txt]
name=Eggman Platform
codefile=WFZ/Generic.cs
codetype=S2ObjectDefinitions.WFZ.EggmanPlatform
[WFZ/EggmanShuttle.txt]
name=Eggman Shuttle
xmlfile=WFZ/EggmanThruster.xml
[WFZ/EggmanThruster.txt]
name=Eggman Thruster
xmlfile=WFZ/EggmanThruster.xml
[WFZ/GrabBar.txt]
name=Grab Bar
codefile=WFZ/GrabBar.cs
codetype=S2ObjectDefinitions.WFZ.GrabBar
[WFZ/GrabPanel.txt]
name=Grab Panel
codefile=WFZ/GrabPanel.cs
codetype=S2ObjectDefinitions.WFZ.GrabPanel
[WFZ/GrabPanelPart.txt]
name=Grab Panel Part
sheet=SCZ/Objects.gif
frame=-16, -16, 32, 32, 1, 69
hidden=true
[WFZ/Hatch.txt]
name=Hatch
sheet=SCZ/Objects.gif
frame=-16, -8, 32, 16, 409, 1
[WFZ/HPlatform.txt]
name=H Platform
codefile=WFZ/Platform.cs
codetype=S2ObjectDefinitions.WFZ.HPlatform
[WFZ/HPlatform2.txt]
name=H Platform 2
codefile=WFZ/Platform.cs
codetype=S2ObjectDefinitions.WFZ.HPlatform2
[WFZ/HPropeller.txt]
name=H Propeller
codefile=WFZ/HPropeller.cs
codetype=S2ObjectDefinitions.WFZ.HPropeller
[WFZ/Hull.txt]
name=Hull
sheet=SCZ/Objects2.gif
frame=-256, -96, 512, 192, 0, 0
[WFZ/HullSeal.txt]
name=Hull Seal
xmlfile=WFZ/HullSeal.xml
[WFZ/LargeLaser.txt]
; i don't think this should even be placed in the scene in the first place,
; but it has a Startup foreach so i guess i'll leave it placeable..?
name=Large Laser
sheet=SCZ/Objects.gif
frame=-24, -112, 48, 256, 464, 0
[WFZ/Laser.txt]
; prop val is unused (even if it's set)
name=Laser
sheet=SCZ/Objects.gif
frame=-72, -8, 144, 16, 81, 198
[WFZ/Launcher.txt]
name=Launcher
codefile=WFZ/Launcher.cs
codetype=S2ObjectDefinitions.WFZ.Launcher
[WFZ/PullChain.txt]
name=Pull Chain
codefile=WFZ/PullChain.cs
codetype=S2ObjectDefinitions.WFZ.PullChain
[WFZ/RotatePlatform.txt]
name=Rotate Platform
codefile=WFZ/RotatePlatform.cs
codetype=S2ObjectDefinitions.WFZ.RotatePlatform
[WFZ/ShipFG.txt]
name=Ship FG
codefile=WFZ/ShipFG.cs
codetype=S2ObjectDefinitions.WFZ.ShipFG
[WFZ/TiltPlatformH.txt]
name=Tilt Platform H
codefile=WFZ/IntervalPlatform.cs
codetype=S2ObjectDefinitions.WFZ.TiltPlatformH
[WFZ/TiltPlatformL.txt]
name=Tilt Platform L
codefile=WFZ/IntervalPlatform.cs
codetype=S2ObjectDefinitions.WFZ.TiltPlatformL
[WFZ/TiltPlatformM.txt]
name=Tilt Platform M
sheet=SCZ/Objects.gif
frame=-24, -4, 48, 8, 320, 99
[WFZ/TiltPlatformV.txt]
name=Tilt Platform V
codefile=WFZ/IntervalPlatform.cs
codetype=S2ObjectDefinitions.WFZ.TiltPlatformV
[WFZ/Tornado.txt]
name=Tornado
xmlfile=WFZ/Tornado.xml
[WFZ/TornadoExplosion.txt]
name=T Explosion
sheet=Global/Items2.gif
frame=-8, -8, 16, 16, 230, 18
hidden=true
[WFZ/Turret.txt]
name=Turret
codefile=WFZ/Generic.cs
codetype=S2ObjectDefinitions.WFZ.Turret
[WFZ/TurretBullet.txt]
name=Turret Bullet
codefile=WFZ/Generic.cs
codetype=S2ObjectDefinitions.WFZ.TurretBullet
[WFZ/TurretPlatform.txt]
name=Turret Platform
codefile=WFZ/IntervalPlatform.cs
codetype=S2ObjectDefinitions.WFZ.TurretPlatform
[WFZ/VPlatform.txt]
name=V Platform
codefile=WFZ/Platform.cs
codetype=S2ObjectDefinitions.WFZ.VPlatform
[WFZ/VPlatform2.txt]
name=V Platform 2
codefile=WFZ/Platform.cs
codetype=S2ObjectDefinitions.WFZ.VPlatform2
[WFZ/VPropeller.txt]
name=V Propeller
sheet=SCZ/Objects.gif
frame=-4, -64, 8, 64, 121, 106
[WFZ/WFZInvBlock.txt]
name=WFZ Inv Block
codefile=Global/InvisibleBlock.cs
codetype=S2ObjectDefinitions.WFZ.WFZInvBlock
[WFZ/WFZSetup.txt]
name=WFZ Setup
hidden=true
[WFZ/WindCurrent.txt]
name=Wind Current
codefile=WFZ/WindCurrent.cs
codetype=S2ObjectDefinitions.WFZ.WindCurrent
