EXEFile=RSDKv3.exe
DataFile=Data.rsdk
RSDKVer=v3
IsV5U=False ; set to True if using the Origins datapack

; format:
; name, file, in-game starting index, individual frame length, total frame count, offset, gap

[R31A]
PaletteCycle1=Flashing Lights:R3A_PalCycle.act:160:32:6

[R51A]
PaletteCycle1=Glowing Rocks:R5A_GlowEffect.act:176:16:4
PaletteCycle2=idk?:R5A_PalCycle.act:160:16:6:0:16
PaletteCycle3=idk 2?:R5A_PalCycle.act:192:16:6:16:16

[R51C]
PaletteCycle1=Conveyor Belt:R5C_PalCycle.act:160:16:6

