name: Update release

#on:
#  push:
#    paths:
#      - update.ini
#    branches:
#      - patch-2 # master

# on: [pushworkflow_dispatch]

permissions:
   contents: write

on: [push, workflow_dispatch]
jobs:
   build:
     runs-on: windows-latest
     
     steps:
       - name: Checkout repository 
         uses: actions/checkout@v4
         
       - name: Setup MSBuild
         uses: microsoft/setup-msbuild@v2
         
       - name: Build projects
         run: |
          msbuild SonLVL.sln /p:Configuration=Release
          
       - name: Create archives
         shell: cmd
         run: |
          set "projects=SonLVL LevelConverter SonAni ObjectLayoutDiff SpriteSheetGen SpritePlotter.NET GetArt.NET S1SSEdit S3SSEdit ObjectLayoutMerge SonPLN"
          mkdir "build"
          for %%a in (%projects%) do powershell -Command "Compress-Archive -Path '%%a/bin/Release' -DestinationPath 'build/%%a.zip' -Force"
          
       - name: Push to build branch
         run: |
          git config --global user.email "sonicretro@github.com"
          git config --global user.name "sonicretro"
          git checkout -b build
          git rm -r .
          cp -r build/* .
          rm -r -force build/
          git add "*.zip"
          git commit -m "Update build"
          git push origin build --force